### ISSUE TITLE
Static Analysis Support

### ISSUE THREAD

**Issue by kageiit** [uber/okbuck#125]
- [x] Lint
- [x] Infer

**Comment by kageiit** [comment]
Infer is supported out of the box with buck

http://fbinfer.com/docs/analyzing-apps-or-projects.html

```
infer -- buck build target
```

**Comment by kageiit** [comment]
Lint is handled in https://github.com/uber/okbuck/pull/228

**Comment by TomMD** [comment]
Resurrecting this issue, and doing so as a buck novice, how does this square with the workflow which seems biased towards buckw?  Can I safely ignore the wrapper target and:

```
./gradlew :okbuck    # generates buck files
infer run -- buck build target  # use buck file
```

Or is the `:okbuck` target a second class citizen in some way?
