### ISSUE TITLE
parameter 'skeleton' && parameter 'proguardConfig' : no such file or directory

### ISSUE THREAD

**Issue by 2BAB** [uber/okbuck#183]
I have a buildType named releaseChangeEnv, and when I build app:src_debug, it failed: 

    → ./buckw build app:src_debug
    [+] PARSING BUCK FILES...0.4s [17%]
    BUILD FAILED: //app:manifest_releaseChangeEnv: parameter 'skeleton': no such file or directory 'app/build/okbuck/releaseChangeEnv/AndroidManifest.xml'

if I remove this buildType, it throws a new exception:

    → ./buckw build app:src_debug
    [+] PARSING BUCK FILES...0.3s [15%]
    BUILD FAILED: //app:bin_release: parameter 'proguardConfig': no such file or directory 'app/build/okbuck/release/proguard.pro'

The plugin version I use is 0.6.0.

**Comment by kageiit** [comment]
Can you try on 0.7.1 ? Some proguard issues were fixed in it.

Feel free to re-open if this is still happening

**Comment by 2BAB** [comment]
This issue is fixed by Updating to 0.8.5, but the Buck not support Data-Binding. Anyway, thanks!
