### ISSUE TITLE
buildTypes -  Custom buildconfig fields not supported?

### ISSUE THREAD

**Issue by srmankala** [uber/okbuck#186]
**Issue:**
If we have custom build config fields as part of buildTypes block BUCK file generate doesn't include them. 
In below example BUCK file generated doesn't have **CUSTOM_PARAMETER** field. ( this seems to be working fine with product flavors) 
e.g 
 buildTypes {
        release {
            buildConfigField "String", "CUSTOM_PARAMETER", "\"release\""
        }
       debug {
            buildConfigField "String", "CUSTOM_PARAMETER", "\"debug\""
        }
 }

**Comment by kageiit** [comment]
they are supported. what plugin are you using. read the README carefully. the new artifact is `com.uber:okbuck:0.7.0`

**Comment by srmankala** [comment]
@kageiit I am using latest. (com.uber:okbuck:0.7.0)

I tried this on latest master(uber/okbuck) as well.

If you see below all the build config fields from product flavors are included but are missing config fields(RELEASE_CUSTOM_CONFIG)  from release buildType. 
Am I missing something here. Please advise

**Gradle build.gradle**
 ` buildTypes {
        debug {
            buildConfigField "boolean", "DEBUG_CONFIG", "true"
            signingConfig signingConfigs.release
            applicationIdSuffix = ".debug"
        }
        release {
            buildConfigField "boolean", "RELEASE_CUSTOM_CONFIG", "true"
            buildConfigField "boolean", "DEBUG_CONFIG", "false"
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt')
        }
    }`

**buck generated build_config**

android_build_config(
        name = 'build_config_devRelease',
        package = 'com.uber.okbuck.example',
        values = [
                'String APPLICATION_ID = "com.uber.okbuck.example.dev"',
                'String BUILD_TYPE = "release"',
                'String FLAVOR = "dev"',
                'int VERSION_CODE = 1',
                'String VERSION_NAME = "1.0"',
                'boolean CAN_JUMP = true',
                'int EXOPACKAGE_FLAGS = 1',
                'boolean XLOG_ENABLED = true',
        ],

**Comment by kageiit** [comment]
@srmankala thanks for the report. Seems like we were missing values from buildTypes and were only consuming ones from product flavors. #200 will fix it
