### ISSUE TITLE
Add the `--offline` flag for gradle source gen rule

### ISSUE THREAD

**Issue by Piasy** [uber/okbuck#189]
Adding this flag would speed up build very much, and dependencies will be downloaded during the execution of `okbuck` task.

**Comment by kageiit** [comment]
I think we should make it an option to add whatever flag user wants for the gradle source gen rule instead of hard coding just a single flag. There might be other flags that may be uaeful

**Comment by Piasy** [comment]
Ya, allow user to add extra flag is a good way.
