### ISSUE TITLE
Adding test resources to a project that does not have any resources should trigger OkBuck run in the buck wrapper.

### ISSUE THREAD

**Issue by tonycosentini** [uber/okbuck#191]
Adding resources to a test source set that does not previously have test resources (this might apply to resources in main source sets too) will not get caught by `buckw`.

You need to manually rerun OkBuck to pick up these changes in generated BUCK.

**Comment by kageiit** [comment]
Yes this is a known issue. buckw currently only detects changes to `res` and not `resources`. Thanks for bringing it up
