### ISSUE TITLE
Duplicate element error

### ISSUE THREAD

**Issue by marcinkwiatkowski** [uber/okbuck#195]
In the following, somehow non typical but still valid project setup, generated buck files cause `duplicate element` error

Gradle files
```groovy
// common build.grade
dependencies {
  testCompile project(":test-support")
}

// test-support build.grade
dependencies {
  compile project(":common")
}
``` 

Generated buck file
```python
# common BUCK
deps = [
 ‘//test-support:src_main',
 ‘//common:src_main',
 ':src_main',
]
```

Error
`duplicate element "//common:src_main"`

Looking at the code, the test rule composer always includes `:${src(target)}` (`':src_main'` in that case). 
If we changed it to `${target.path}:${src(target)}`, the de-dup logic would handle the duplicate and the output would be:
```python
deps = [
 ‘//common:src_main',
 ‘//test-support:src_main',
]
```

The other option could be not adding target dependency to the Scope, if it's path is same as the target's path.

**Comment by kageiit** [comment]
I like the second approach better as it still keeps the generated BUCK files be more readable. Thanks for opening the issue. This is definitely a valid use case.
