### ISSUE TITLE
OkBuck is not working for the WordPress project

### ISSUE THREAD

**Issue by eljobe** [uber/okbuck#219]
I've just posted this in the Buck Google Group:
https://groups.google.com/forum/#!topic/buck-build/s4-qtB4J1XY

In summary, we have forked the WordPress project so that we can compare Gradle and Buck performance, and we've quickly run into a roadblock attempting to generate a good set of BUCK files for the project using OkBuck. We aren't sure if it is a bug in BUCK or the okbuck plugin, and we're asking for help from the experts. Please weigh in on that thread if you see something obvious.

**Comment by kageiit** [comment]
Fixed in https://github.com/gradle/perf-android-medium/pull/1
