### ISSUE TITLE
Support for extra resource directories

### ISSUE THREAD

**Issue by cwoodwar6** [uber/okbuck#221]
We don't define flavors, they just exist and Gradle is happy. They once existed as flavors but are no longer defined that way. Probably due to some magic under the hood. Either way, here is the situation:

I have the folder `module/main/res` with an `android_resource` configuration named `res_main`. There is a folder `module/x/res` that is also defined. This is the inexplicit flavor. OkBuck sees it fine, it defines a BUCK configuration for it named `res_x`. In `module/x/res` we reference a string in the main resources. Buck isn’t able to find that string because `res_x`isn’t declaring `res_main` as a dependency.

I've found this edge case for our project but could be likely others have seen it. Simply adding `res_main` as a dependency of `res_x` solved the issue.

I've started investigating myself but I find myself low on time. Filing this issue to perhaps encourage others to help or to just make others aware of this. Looks like OkBuck just simply needs to properly define the resource dependency.

**Comment by kageiit** [comment]
okbuck defines the dependency based on what it gets from the basevariant api. It cannot make special assumptions because that might break someone else's use case. Seems like you can get around this by just defining a flavor. I would suggest to try that first.

**Comment by kageiit** [comment]
Repor: https://github.com/runningcode/okbuck/tree/no/repro

**Comment by kageiit** [comment]
There is no clean way for okbuck to infer that resources in one directory are referring to resources in another without an explicit dependency. My suggestion would be to move the resources in x to another gradle module and add a dependency on it. Buck only allows one directory of res/assets per `android_resource` rule. Gradle manages this by copying resources from all the included folders into an intermediates directory, which we can replicate, but will add additional cost upfront. This can be avoided by adding the explicit dependency by making the module instead

Also, is there a reason the resources cannot be just moved into main from x? Whats the rationale for keeping them in that directory if there is no explicit flavor/build type?

**Comment by kageiit** [comment]
Closing due to suggested workaround. Feel free to let me know if anything is missing and I will reopen as needed
