### ISSUE TITLE
Generated gradle genrules contain absolute paths, breaking caching

### ISSUE THREAD

**Issue by seanabraham** [uber/okbuck#237]
The specific breaking case here is the gradle genrule that okbuck has to support SqlDelight

The output in the BUCK file looks like:
```
genrule(
	name = 'gradle_sourcegengenerateReleaseSqlDelightInterface',
	srcs = glob([
		'src/main/sqldelight/**/*.sq',
		'src/release/sqldelight/**/*.sq',
	]),
	out = 'gradle_sourcegengenerateReleaseSqlDelightInterface_out',
	bash = '/Users/some_user/projects/some/project/gradlew -p /Users/some_user/projects/some/project :core:generateReleaseSqlDelightInterface --offline -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true --stacktrace && cp -a /Users/some_user/projects/some/project/core/build/generated/source/sqldelight $OUT',
)
```

This is problematic for the same reason all absolute paths in BUCK files are problematic: it can break cache consistency as everyone's local machines can potentially compute rule keys differently.

**Comment by kageiit** [comment]
This is no longer an issue as okbuck does not use gradle source gen rules anymore
