### ISSUE TITLE
Trying to merge incompatible /manifest/application/activity[@name=com.facebook.accountkit.ui.AccountKitActivity] element:

### ISSUE THREAD

**Issue by vanniktech** [uber/okbuck#240]
Output:

```diff
  <activity android:name=com.facebook.accountkit.ui.AccountKitActivity>
--    @android:label = @string/com_accountkit_button_log_in
--    @android:launchMode = singleTop
      @android:name = com.facebook.accountkit.ui.AccountKitActivity
++    @android:theme = @style/FacebookAccountKitTheme
--    @android:theme = @style/Theme.AccountKit
--    @android:windowSoftInputMode = adjustResize
++    @tools:replace = android:theme
++    @xmlns:tools = http://schemas.android.com/tools
```

Seems like `tools:replace="android:theme"` is not handled correctly. I'm manually adding this activity and overriding the theme in my manifest.

I'm using Version 0.9.5 is there anything else that you guys will need?

**Comment by hzsweers** [comment]
afaik this is because buck still uses the old manifest merger, but I'll defer to Gautam on this

**Comment by vanniktech** [comment]
This might make sense yeah, I also see some other merge errors in the output.

**Comment by kageiit** [comment]
yes buck does not support the new manifest merger attributes yet. `tools:replace` being one of them

**Comment by vanniktech** [comment]
It also [seems like](https://github.com/facebook/buck/issues/299) this is not a priority anyways. Is there any way to get around this?

**Comment by kageiit** [comment]
@vanniktech Wait for https://github.com/facebook/buck/pull/1018 to merge :)

**Comment by kageiit** [comment]
Or if you want to use it sooner, you can create a fork of buck and cherry pick this change over. `./buckw` supports custom forks. You can set the 

```
okbuck {
  wrapper {
    repo = "<fork-url>"
  }
}
```

and regenerate the wrapper

**Comment by vanniktech** [comment]
I think I'll wait for the official one as this is not blocking me really. I just wanted to give okbuck a try

**Comment by kageiit** [comment]
No action on okbuck part. need to wait for https://github.com/facebook/buck/pull/1018 to merge
