### ISSUE TITLE
Error: resource directory 'buck-out/bin/.okbuck/cache/__unpack_com.google.firebase...#aar_unzip__res' does not exist

### ISSUE THREAD

**Issue by cuchas** [uber/okbuck#250]
I'm trying to use okbuck with my project but I'm getting dependency errors like this one:

Error: resource directory 'buck-out/bin/.okbuck/cache/__unpack_com.google.firebase...#aar_unzip__res' does not exist

$MY_PROJECT/__src_debug#dummy_r_dot_java_rdotjava_src__/$MY_PACKAGE/R.java:linenumber error ';' expected

public static int drawable-hdpi=hexadress

Any idea why I could getting this errors? This happens with many other drawables inside the same package.

**Comment by kageiit** [comment]
What version of buck are you using? do you still see the issue if you set the buck sha to latest in `.buckversion` ?

**Comment by cuchas** [comment]
Yes I do, I'm using buck v2016.11.11.01 it is the latest version!

**Comment by kageiit** [comment]
I would recommend not using buck from brew. use `buckw` instead . look for examples in the sample project in this repo. they point to a buckversion file as documented in https://buckbuild.com/concept/buckversion.html

**Comment by kageiit** [comment]
Closing since correct buck version was not used. Please comment if you still have issues with `buckw`

**Comment by cuchas** [comment]
Sorry, I tried downloading and compiling buck but it still doesn't work. It looks the script tries to read res folder in every aar file, but firebase-core does not have one, any other suggestions?

buck version af1fef7f44a35cf34a54a4a5f67bc159f0fabe0a

PS: How did you know I installed buck using brew?

**Comment by runningcode** [comment]
always use the buck wrapper with `./buckw` never call any other installed buck version from the command line with `buck`
