### ISSUE TITLE
Warnings when running buck wrapper

### ISSUE THREAD

**Issue by vanniktech** [uber/okbuck#255]
I get the following warnings when I try to run the wrapper regardless of the command:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'files'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'files'
```

I am using version 0.10.1 of OkBuck. Is there any other information you guys need?

**Comment by hzsweers** [comment]
do you have a sample project we could repro on?

**Comment by vanniktech** [comment]
This even happens when I create a new Android Project from AS.

[Here's my playground](https://github.com/vanniktech/okbuck-playground) where if I execute buck wrapper I get this warning.

**Comment by kageiit** [comment]
Seems like you have an older version of watchman/python. Can you confirm what versions of both you have available in path. To suppress the warnings, you can also uninstall watchman during testing

**Comment by vanniktech** [comment]
```
Python 2.7.12
Watchman 4.7.0
```

**Comment by kageiit** [comment]
Unable to reproduce your error on the playground repo. Is it blocking you from building? Can you try to repro on a colleague, friend's computer?

**Comment by vanniktech** [comment]
Nope not blocking at all it just emits those warnings in the beginning and then continues

**Comment by vanniktech** [comment]
Still happening with `0.12.1`. Is there any more information I could give you?

**Comment by kageiit** [comment]
Should be fixed in v0.13.0

**Comment by vanniktech** [comment]
I just checked and it isn't

**Comment by kageiit** [comment]
Uou need to regenerate your wrapper. Can you try again after you do so?

**Comment by vanniktech** [comment]
I did so with `./gradlew :buckWrapper`

**Comment by kageiit** [comment]
Same error with new wrapper?

**Comment by vanniktech** [comment]
Yup same error

**Comment by vanniktech** [comment]
@kageiit also with the latest version (0.14.3) - [I just updated](https://github.com/vanniktech/okbuck-playground)

**Comment by vanniktech** [comment]
This is the cause for #334 :/

**Comment by vanniktech** [comment]
Managed to fix this with the following approach:

```
watchman watch-del-all
touch ~/path/project/.watchmanconfig
```

The reason it happened to me was because I have a Git repository in my home path.
