### ISSUE TITLE
ImportError: No module named buck_parser

### ISSUE THREAD

**Issue by devilmac** [uber/okbuck#257]
Hi,
I'm trying to use OkBuck to build my project but I get this error:

MBP-di-Federico:MyProject federico$ ./buckw build appDebug
Shutting down nailgun server...
Using watchman.
Warning raised by BUCK file parser: Traceback (most recent call last):
Warning raised by BUCK file parser:   File "/Volumes/HDD Mac/AndroidStudioProjects/MyProject/.buckd/tmp/buck_run.n311S0/buck_python_program5486352555453887462/__main__.py", line 8, in "module"
Warning raised by BUCK file parser:     from buck_parser import buck
Warning raised by BUCK file parser: ImportError: No module named buck_parser
[+] PARSING BUCK FILES...1,6s
BUILD FAILED: Parse error for build file /Volumes/HDD Mac/AndroidStudioProjects/MyProject/app/BUCK:
Parser exited unexpectedly

What I understand is that It seems a module named `buck_parser` not exists inside the BUCK file within `app` folder, but this BUCK file was generated by OkBuck and actually there's nothing named `buck_parser` inside the file.

Thanks for your help.

**Comment by kageiit** [comment]
What version of buck are you using? do you still see the issue if you set the buck sha to latest in .buckversion ?

**Comment by devilmac** [comment]
@kageiit 
I'm using this version of Buck:
```
federico$ brew install buck
Warning: facebook/fb/buck-2016.11.11.01 already installed
```
I don't have the `.buckversion` file in my project.

**Comment by kageiit** [comment]
Can you use a more recent version of buck.

I would recommend not to use brew's buck. Use `buckw` instead that can be generated with `./gradlew buckWrapper`

**Comment by kageiit** [comment]
Closing because right version of buck was not used. Please comment if `buckw` has not solved the issue

**Comment by devilmac** [comment]
Hi @kageiit,
I added the .buckversion file to my project with te latest version of Buck (this one: 6197e7aa555c0cb1100d65bc1e20c83f692c5c63) and now it seems building my project with Buck works well.
Thanks a lot for the help.

**Comment by zoom2manoj** [comment]
I have added this file also but still, getting same error as below when I hitting "```
# From the root `cross-platform-scale-2015-demo/` directory
# demo_app_android is an alias in .buckconfig for //android:demo-app. Either works.
buck build demo_app_android
```" command: 


`Traceback (most recent call last):
  File "D:\react_native\test_cases\buck\bin\..\programs\buck.py", line 8, in <mo
dule>
    from buck_tool import BuckToolException, RestartBuck, install_signal_handler
s
  File "D:\react_native\test_cases\buck\programs\buck_tool.py", line 15, in <mod
ule>
    from pynailgun import NailgunConnection, NailgunException
  File "D:\react_native\test_cases\buck\third-party\nailgun\pynailgun\__init__.p
y", line 1, in <module>
    from ng import NailgunConnection, NailgunException
ModuleNotFoundError: No module named 'ng'`.

Can anyone support please what am I missing during configuration for Buck set-up.
