### ISSUE TITLE
targetsdkversion  conflict

### ISSUE THREAD

**Issue by androidhuoniao** [uber/okbuck#270]
![image](https://cloud.githubusercontent.com/assets/4191583/20998832/8bd8f0aa-bd4b-11e6-9881-985897b2841d.png)

**Comment by kageiit** [comment]
This is a legit error in the old manifest merger that buck currently uses

You may have to wait for https://github.com/facebook/buck/pull/1018 to merge as the new manifest merger does not account for this as an error

**Comment by kageiit** [comment]
Closing since this is not an okbuck issue

**Comment by ChaitanyaPramod** [comment]
@kageiit Can you suggest a work-around we can use to evaluate okbuck with our project until upstream lands the change?

**Comment by kageiit** [comment]
@ChaitanyaPramod You can set your target sdk to the highest version so that it is >= whats coming from any transitive libraries
