### ISSUE TITLE
Explore making changes to rule `deps` to only add direct dependencies.

### ISSUE THREAD

**Issue by raviagarwal7** [uber/okbuck#277]
Transitives ones' are already included by rules in dependent projects. This will make BUCK files smaller and more readable.

**Comment by kageiit** [comment]
This will create problems with exclude rules in dependency declarations. Needs more thought

**Comment by kageiit** [comment]
This is not needed given the api/impl support added in AGP 3.x makes this obsolete. This will be resolved as soon as #568 merges. Closing for now
