### ISSUE TITLE
No R2 class for dealing with ButterKnife

### ISSUE THREAD

**Issue by sadegh** [uber/okbuck#295]
Hi,

I am using ButterKnife in my project but when I run `./buckw build //app:bin_debug` I get ` error: element value must be a constant expression`. According to [wiki](https://github.com/uber/okbuck/wiki/Known-caveats#butterknife) I have to use `R2` instead of `R`, but I don't see any R2 class.
So my question is how exactly `R2` could generated?

Thank you.

**Comment by kageiit** [comment]
You need to apply the butterknife gradle plugin on apps as well

https://github.com/JakeWharton/butterknife#library-projects

Since buck builds all code as libraries. You then need to replace all R with R2 in your imports and code

**Comment by sadegh** [comment]
oh, I didn't notice that part. thanks :grinning:
