### ISSUE TITLE
Not support custom projectDir

### ISSUE THREAD

**Issue by stat0s2p** [uber/okbuck#296]
i use a custom projectDir in settings.gradle:
```gradle
include ':app'
include ':weex_sdk'
//include 'plugin'
project(':weex_sdk').projectDir = new File('sq-weex/android/sdk')
```
then i run gradle task okbuck to genernate BUCK file.
the app BUCK file deps field use the project name //weex_sdk as the correct location is //sq-weex/android/sdk:
```
android_resource(
	name = 'res_main',
	res = 'src/main/res',
	package = '***',
	assets = 'src/main/assets',
	resource_union = True,
	deps = [
		'//weex_sdk:res_main',
		'//weex_sdk:res_sdk',
	],
```
So i run `buckw build appRelease` it tell me at //weex_sdk not found a buck file.
i think it should use the projectDir but not project name in BUCK file dept field.

**Comment by kageiit** [comment]
Can you just move the project directory to the correct name? Whats preventing you from doing that? This is not a usecase we can support easily as it complicates the api and logic a lot internally

**Comment by kageiit** [comment]
okbuck already respects what is given by `project.path` to refer to generated project rules

you can instead do 

```
include ':sq-weex:android:sdk`
```

**Comment by stat0s2p** [comment]
@kageiit weex_sdk is a forked third part library(https://github.com/alibaba/weex). we add in project using git submodule so can not simply change the directory structure.

your include code works thank you.

**Comment by kageiit** [comment]
Great
