### ISSUE TITLE
MultiDex Issue

### ISSUE THREAD

**Issue by yelinaung** [uber/okbuck#304]
Hello,

First of all, thanks for creating awesome plugin!

I've having some issues with MultiDex and okbuck. I've created a sample app at [https://github.com/yelinaung/BuckTest](https://github.com/yelinaung/BuckTest).

I can successfully run `./buckw install -r //app:bin_debug ` and the app starts. If I understand correctly logs are saying that the MultiDex is disabled ?

```

 System  W  ClassLoader referenced unknown path: /data/app/co.ninetynine.bucktest-1/lib/arm64
    art  W  Class android.support.multidex.MultiDex failed lock verification and will run slower.
         W  Common causes for lock verification issues are non-optimized dex code
         W  and incorrect proguard optimizations.
MultiDex I  VM with version 2.1.0 has multidex support
         I  install
         I  VM has multidex support, MultiDex support library is disabled.
         I  install
         I  VM has multidex support, MultiDex support library is disabled.
    art  W  Class android.support.v4.util.SimpleArrayMap failed lock verification and will run slower.
         W  Class android.support.v4.app.FragmentManagerImpl failed lock verification and will run slower.
         W  Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(an
            droid.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridde
            n the package-private method in android.graphics.drawable.Drawable
         W  Class android.support.v7.widget.AppCompatDrawableManager failed lock verification and will run slower.
         W  Class android.support.v4.util.LruCache failed lock verification and will run slower.
         W  Class android.support.v4.content.ContextCompat failed lock verification and will run slower.
         W  Class android.support.v7.content.res.AppCompatResources failed lock verification and will run slower.
         W  Class android.support.v7.widget.TintContextWrapper failed lock verification and will run slower.
```
I also have looked at [wiki](https://github.com/uber/okbuck/wiki/Multidex-Configuration-Guide) for the configuration guide and configured accordingly [here](https://github.com/yelinaung/BuckTest/blob/master/app/build.gradle#L57-L71). Is there anything wrong with the config ?

I've integrated the same config in the product that I am working on. The logs are the same and the app didn't function properly.

**Comment by yelinaung** [comment]
Update : I've found the bug in the product app and after fixing it, things seem running fine. But I am still wondering why the message still show `MultiDex support library is disabled` despite it's enabled in the `app/build.gradle`

**Comment by ChaitanyaPramod** [comment]
@yelinaung That line is harmless (and logged at info level). It means that the host OS itself will load all the dex files and support-multidex library doesn't have to do that.

**Comment by yelinaung** [comment]
@ChaitanyaPramod Argh got it. I will close this issue for now. Thanks for the answer and Merry Christmas! :christmas_tree:
