### ISSUE TITLE
Issue with OkBuck + Realm

### ISSUE THREAD

**Issue by paulononaka** [uber/okbuck#305]
Hi! My build and APK are successfully generated, but when I run the app an error is raised, forcing close the app. If I build the same dependencies with Gradle, not using OkBuck, it runs perfectly. Logcat:

```
E/AndroidRuntime( 3447): FATAL EXCEPTION: main
E/AndroidRuntime( 3447): Process: mobile.nonaka.com.nonakaapp.ci, PID: 3447
E/AndroidRuntime( 3447): java.lang.ExceptionInInitializerError: RealmTransformer doesn't seem to be applied. Please update the project configuration to use the Realm Gradle plugin. See https://realm.io/news/android-installation-change/
E/AndroidRuntime( 3447): 	at io.realm.RealmConfiguration.<clinit>(RealmConfiguration.java:77)
E/AndroidRuntime( 3447): 	at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:428)
E/AndroidRuntime( 3447): 	at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:391)
E/AndroidRuntime( 3447): 	at mobile.nonaka.com.nonakaapp.NONAKAApplication.onCreate(NONAKAApplication.java:44)
E/AndroidRuntime( 3447): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
E/AndroidRuntime( 3447): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
E/AndroidRuntime( 3447): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/AndroidRuntime( 3447): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime( 3447): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3447): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3447): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime( 3447): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3447): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 3447): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime( 3447): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime( 3447): 	at dalvik.system.NativeStart.main(Native Method)
```

NONAKAApplication.java line 44 has this code:
```
            RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                    .schemaVersion(1)
                    .encryptionKey(realmKeyProvider.getRealmKey())
                    .deleteRealmIfMigrationNeeded()
                    .build();
```

https://realm.io/news/android-installation-change did not help. This is my Gradle configuration that I used to generate the Buck files:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "io.realm:realm-gradle-plugin:2.2.1"
    }
}

apply plugin: 'realm-android'
```

Versions:
OkBuck 0.13.1
Realm 2.2.1
Gradle 3.2
Android Gradle Plugin 2.2.3
Android Studio 2.2.3
minSdkVersion 18
targetSdkVersion 25
compileSdkVersion 25
buildToolsVersion '25.0.2'

Thanks a lot!

**Comment by Zhuinden** [comment]
That's because OkBuck doesn't support the Transform API yet.

https://github.com/realm/realm-java/issues/3971

**Comment by paulononaka** [comment]
@Zhuinden didn't notice that. Thanks a lot! Does anyone know though if it is possible to use Realm without this Transform API?

**Comment by Zhuinden** [comment]
The last Realm that does not use the Realm-Transformer API is `compile "io.realm:realm-android:0.87.5"`

In that version of Realm, RealmObjects cannot have custom methods, and custom logic in getters/setters.

Also, RealmResults are live in transactions, so you need to reverse iterate them instead of using `for(Blah blah: blahs)`.

**Comment by paulononaka** [comment]
@Zhuinden thanks man. It helped me a lot!

**Comment by kageiit** [comment]
Transform api support is actually available in okbuck, but it is not documented yet. It's a bit of work to setup right now, so we are working to make it more plug and play and will document it fully at that point.

**Comment by paulononaka** [comment]
@kageiit cool man. Could you share with me how to make it work? Perhaps a working configuration sample. I'm willing to make it work, even though it is still not so simple.

**Comment by kageiit** [comment]
cc @malbano can add some comments on how to setup transforms with okbuck

**Comment by meierjan** [comment]
As supporting the Transformer is in the Planned section. Is there ANYTHING you can say about when this is happening?

**Comment by kageiit** [comment]
@malbano is opening a PR in the next few days i believe

**Comment by meierjan** [comment]
Uh that would be awesome 👍🏼

**Comment by malbano** [comment]
I created a PR to add the missing part to support transform api. Transform-cli is a command line utility that mimes the behaviour of android transform api, creating a transform invocation that processes all the input jars. Note that the transform step is plugged before the dex one and applied once to all the modules of the app (i.e. it disables predexing, so it may be worth to create a different build type). The transform needs an empty or a single argument constructor accepting a File, i.e. a configuration for the transform itself. 
Transforms accepting the gradle project as argument in the constructors are not currently supported. I will open an additional PR with an example soon. 
Happy Transforming!

**Comment by Zhuinden** [comment]
I wonder if OkBuck works with google/dagger Hilt.

**Comment by mochadwi** [comment]
Willing to know that if OkBuck also supports Hilt

**Comment by kageiit** [comment]
Please open a separate issue for Hilt as it is not relevant to Realm. if the question is about the gradle plugin that does bytecode transformation, it is not directly supported. It is however possible to add that support similar to how okbuck supports jarinfer as that is a byteode transformation as well. It is possible to use hilt without the gradle plugin that supports bytecode transformation - https://dagger.dev/hilt/quick-start

**Comment by Zhuinden** [comment]
Hilt relies on the Gradle bytecode transform api

**Comment by kageiit** [comment]
hilt transforms post compile instead of pre proguard/dex/apk steps so its lot easier to add support for it
