### ISSUE TITLE
Package not found when use buildConfigField of enum type

### ISSUE THREAD

**Issue by fseba** [uber/okbuck#306]
Hi.

I am adding a buildConfigField with an Enum value that depends on buildType.
```
 buildTypes {
        release {
                   buildConfigField 'com. ... .MyEnum', 'ENUM_VBLE',
                                 'com. ... .MyEnum.VALUE_RELEASE´
         }
        debug {
                   buildConfigField 'com. ... .MyEnum', 'ENUM_VBLE',
                                 'com. ... .MyEnum.VALUE_DEBUG'
         }
```
I am having the next error:

/home/travis/build/ ... /buck-out/gen/app/__build_config_devDebug#gen_java_android_build_config__/BuildConfig.java:11: error: package com.mypackage.MyEnum does not exist

**Comment by kageiit** [comment]
I dont think this will work. buck compiles `BuildConfig.java` separately from the rest of the code. This means buildconfig fields can only be primitives or java/android sdk imports. If you have custom enum code that is part of your codebase, buck will not be able to see them. You have a few options

- Generate a String buildConfigField instead and in your code convert it to the enum using `MyEnum.valueOf(BuildConfig.ENUM_VBLE_STRING)`
- Generate two copies of `MyEnum` and define them differently in debug and release source sets (i.e dont put the enum class in the main source set) and refer to that enum directly in code

**Comment by ChaitanyaPramod** [comment]
Probably a separate issue but I get a similar error when I use android classes in BuildConfig
```java
buildConfigField "int", "LOG_PRIORITY", "android.util.Log.INFO"
```
Using the above fails buck build with "package android.util does not exist"

**Comment by fseba** [comment]
Ok. So, I will set this programmatically in **MainApplication.java**.
Thank you very much!

**Comment by kageiit** [comment]
@ChaitanyaPramod seems like buck does not add anything to the classpath or bootclasspath when compiling buildconfig

https://github.com/facebook/buck/blob/c1bf24631f4cba93602c92aa947b8f66d62534f8/src/com/facebook/buck/android/AndroidBuildConfigJavaLibrary.java#L61

You can get around your issue by hardcoding the int value an adding a comment in your gradle file as to what that integer value means. These values are already final and dont change so it might be fine. Another option is to make these constants defined in a separate java class file similar to what I mentioned above and define that file differently based on build type

**Comment by kageiit** [comment]
Feel free to open an issue against buck if you feel it should support android classes in buildconfig. I am closing this issue as it is not an okbuck issue and there are available workarounds
