### ISSUE TITLE
Building fails if a library does not contain a `res` folder

### ISSUE THREAD

**Issue by chrislacy** [uber/okbuck#314]
To reproduce:
1. Add the following to `libraries/common/build.gradle`:
`compile 'com.google.firebase:firebase-core:9.4.0'`
2. Build the `app` project (I did so via `./buckw install --run appDevDebug`).

Observe building fails with the following error:

```
ERROR: resource directory 'buck-out/bin/.okbuck/cache/__unpack_com.google.firebase.firebase-core-9.4.0.aar#aar_unzip__/res' does not exist

BUILD FAILED: //app:bin_devDebug#aapt_package failed with exit code 1:
aapt_package
stderr: ERROR: resource directory 'buck-out/bin/.okbuck/cache/__unpack_com.google.firebase.firebase-core-9.4.0.aar#aar_unzip__/res' does not exist
```

Seemingly this library doesn't contain a `res` folder. Note that if one manually creates an empty `res` folder at the expected location (`buck-out/bin/.okbuck/cache/__unpack_com.google.firebase.firebase-core-9.4.0.aar#aar_unzip__/res`), the build will complete successfully.

**Comment by kageiit** [comment]
This is a bug in buck. There is a ticket open for it already.
https://github.com/facebook/buck/issues/1055

Closing this because okbuck cannot solve this problem. The aar is not following the spec. More details in the linked ticket
