### ISSUE TITLE
BUILD FAILED: Must set ANDROID_SDK

### ISSUE THREAD

**Issue by h777arsh** [uber/okbuck#317]
Hello Guys,
**BUILD FAILED: Must set ANDROID_SDK to point to the absolute path of your Android SDK directory.**

I'm getting problem when running ./buckw build //app:src_debug command,
I already set my environment variable for SDK and NDK.

Thanks.

**Comment by hzsweers** [comment]
What's the output of running `echo $ANDROID_SDK`?

**Comment by h777arsh** [comment]
Its empty. so i set again and try to execute command but it gave me same error then i again set path before command and now it works :) 

Thanks for help.
Cheers

**Comment by bishopmatthew** [comment]
I'm having the same problem but my ANDROID_SDK is set
```
$ echo $ANDROID_SDK                                                                                                                                              
/usr/local/Cellar/android-sdk/24.1.1_1
$ ./buckw build //app:bin_fastDebug                                                                                                                                 
[-] PROCESSING BUCK FILES...FINISHED 0.0s 🐇
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)
[+] BUILDING...2.2s [64%] (224/347 JOBS, 77 UPDATED, 77 [22.2%] CACHE MISS)
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
BUILD FAILED: Must set ANDROID_SDK to point to the absolute path of your Android SDK directory.
```

**Comment by bishopmatthew** [comment]
Really sorry, turns out it was a typo (24.1.1_1 should have been 24.4.1_1). Ugh I spent forever looking at the difference between the two and never noticed it.
