### ISSUE TITLE
Failed to notify build listener

### ISSUE THREAD

**Issue by ramden** [uber/okbuck#319]
Hello.
I know buck (and okbuck) does not support Windows (I am using Windows 10 Pro) but I ask anyways, maybe it actually can work this issue is removed.

I am using cygwin, setup my os (installed ant and other dependencies) and buck is building at insane speed, which is **great**!

When it comes to the last step to notify gradle about it, it fails with following error:

> ...
BUILD SUCCESSFUL
Total time: 4.184 secs
>
> Stopped 0 worker daemon(s).
Received result Failure[**value=org.gradle.internal.event.ListenerNotificationException: Failed to notify build listener.**] from daemon DaemonInfo{pid=15944, address=[e63d40dd-8948-4a65-9a73-81faf8f44738 port:27871, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], state=Idle, lastBusy=1484076726179, context=DefaultDaemonContext[uid=3e38af56-6e68-43c2-a8bf-aabd93810812,javaHome=C:\Program Files\Java\jdk1.8.0_77,daemonRegistryDir=C:\Users\dr\.gradle\daemon,pid=15944,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=4G,-Dfile.encoding=windows-1252,-Duser.country=GB,-Duser.language=en,-Duser.variant]} (build should be done).
>
>
> FAILURE: Build failed with an exception.
> * What went wrong:
> Failed to notify build listener.

Would you suggest this is a pure Windows issue or something with gradle in general?

I am using gradle 3.3 here

**Comment by kageiit** [comment]
If you are using the android gradle plugin, it might be related to a bug in that. Try to upgrade to the latest version (2.3.0-beta2) of the android gradle plugin and see if that helps.

Related google bug: https://code.google.com/p/android/issues/detail?id=224994

**Comment by kageiit** [comment]
Closing since this is not an okbuck bug. Please comment if there is any other issue
