### ISSUE TITLE
Configuration with name 'buckLint_deps' not found.

### ISSUE THREAD

**Issue by hai-nguyen** [uber/okbuck#322]
Hi,

We got this message when trying to run `okbuck` task: `Configuration with name 'buckLint_deps' not found.`

Is there any way I can skip the lint check step? In our case, we need to skip Lint check due to some 3rd libraries we are using.

Thanks.

**Comment by kageiit** [comment]
You can disable lint entirety using

```
okbuck {
  lint {
    disabled = true
  }
}
```

**Comment by pchmielowski** [comment]
@kageiit Where should I put this code?

**Comment by runningcode** [comment]
inside the okbuck block in your root build.gradle. check the okbuck repo for a sample.

**Comment by BingranLi** [comment]
@kageiit I also got the same error. Is there a way to fix it without disabling lint?

**Comment by kageiit** [comment]
okbuck.lint.version is not mandatory. The default version is inferred from the Android Gradle plugin version

**Comment by kageiit** [comment]
The default version is set during okbuck initialization here: https://github.com/uber/okbuck/blob/master/buildSrc/src/main/java/com/uber/okbuck/extension/LintExtension.java#L24 so that is used if no user supplied value exists

**Comment by TonyTangAndroid** [comment]
For anyone who is wondering the compilable code block to make it work without disabling the link check, please refer to this example 

```
okbuck {
    lint {
        version = '26.3.2'
    }
}
```
[26.3.2](https://mvnrepository.com/artifact/com.android.tools.lint/lint/26.3.2) is the latest version of `com.android.tools.lint`.

**Comment by NickFirmani** [comment]
Hey folks, I think that this could use some more investigation, the two options to work around this right now are either disabling lint or forcing it to use a specific version, which then breaks `//...`

I've created a sample project here: https://github.com/NickFirmani/android-template/tree/f5ec67d14042159e907b1b9375e2bcecea88ac56 that reproduces this problem hermetically

**Comment by kageiit** [comment]
Thanks for providing a sample @NickFirmani . We will take a look

**Comment by stargt** [comment]
i've encountered same problem.

```
* What went wrong:
Execution failed for task ':MODULE_NAME:okbuck'.
> Configuration with name 'buckLint_deps' not found.
```

How can I solve it?

**Comment by kageiit** [comment]
Should be fixed in latest version
