### ISSUE TITLE
Main manifest has <uses-sdk android:targetSdkVersion='23'> but library uses targetSdkVersion='24'

### ISSUE THREAD

**Issue by regisdaniel** [uber/okbuck#327]
Trying to start using buck, but, when I try to run
./buckw build appDebug

The following error appears:
```
Main manifest has <uses-sdk android:targetSdkVersion='23'> but library uses targetSdkVersion='24'
```

I can't change manifest to run against SDK 24. How could I address this?
Here is my config file

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.github.okbuilds:okbuild-gradle-plugin:0.4.0'
    }
}

repositories {
    jcenter()
}

apply plugin: 'com.github.okbuilds.okbuck-gradle-plugin'
okbuck {
    buildToolVersion "25.0.2"
    target "android-23"
}
```

**Comment by kageiit** [comment]
You need to wait till https://github.com/facebook/buck/pull/1018 merges (its close to merge) and use the `tools:replace` marker (https://developer.android.com/studio/build/manifest-merge.html) in your application manifest to override what is coming from libraries.

**Comment by kageiit** [comment]
https://github.com/facebook/buck/pull/1018 has been merged and you can update your `.buckversion` to get the update and use the tools marker to perform the replacement
