### ISSUE TITLE
Which Plugin should I use?

### ISSUE THREAD

**Issue by regisdaniel** [uber/okbuck#328]
I started to read about buck and okbuck last night and it seems to be aweosome.

But, I'm a little bit confused about which libraries should I use to make it work...

The Readme and this [link](https://speakerdeck.com/kageiit/lightning-fast-android-builds-with-gradle-plus-buck) instructs to use:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.uber:okbuck:0.14.3'
    }
}

repositories {
    jcenter()
}

apply plugin: 'com.uber.okbuck'
```

but, reading some issues, I could see that some people are using 

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.github.okbuilds:okbuild-gradle-plugin:0.4.0'
    }
}

repositories {
    jcenter()
}

apply plugin: 'com.github.okbuilds.okbuck-gradle-plugin'
```

that appear to be newer that the first.

Also, the command

```
./gradlew :buckWrapper
```

returns a error when we use the second option, since this tasks appear don't to exists.

Could anybody guides me?

Thanks a lot!

**Comment by kageiit** [comment]
Please use `com.uber:okbuck:0.14.3` i.e whatever is in the current README. The old plugin group id is no longer in use
