### ISSUE TITLE
buckw test - does not run tests

### ISSUE THREAD

**Issue by vanniktech** [uber/okbuck#334]
When I execute `buckw test` on a [really simple project](https://github.com/vanniktech/okbuck-playground) no tests are executed. However the default [ExampleUnitTest](https://github.com/vanniktech/okbuck-playground/blob/master/app/src/test/java/com/vanniktech/okbuck/ExampleUnitTest.java) that Android Studio generates exists. Running `./gradlew test` executes also that test.

Is there something wrong with my set up?

The output is 

```java
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'files'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'files'
[-] PROCESSING BUCK FILES...FINISHED 0.0s 🐇
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.2s (0/0 JOBS, 0 UPDATED)
[-] TESTING...FINISHED 0.0s
RESULTS FOR ALL TESTS
TESTS PASSED (NO TESTS RAN)
```

Version used: 0.14.3

**Comment by kageiit** [comment]
You need to use the custom  [BuckRobolectricTestRunner](https://github.com/uber/okbuck/blob/master/libraries/robolectric-base/src/main/java/com/uber/okbuck/BuckRobolectricTestRunner.java) to make your tests work with buck.

Plan to upstream this to robolectric as the project has new maintainers now

**Comment by vanniktech** [comment]
Okay cool although the unit test doesn't require Robolectric to be present since it's a plain junit test.

**Comment by kageiit** [comment]
Hmm, I see that the tests ran in your sample project

```
./buckw test
 NO PREVIOUS SUCCESSFUL OKBUCK RUN
 RUNNING OKBUCK...

 DELETED OLD BUCK FILES
Parallel execution is an incubating feature.
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
:setupOkbuck
:app:okbuck
:okbuck

BUILD SUCCESSFUL

Total time: 1.192 secs

 PROCEEDING WITH BUCK

Using watchman.
[-] PROCESSING BUCK FILES...FINISHED 0.1s [100%] 🐳  New buck daemon
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 3.3s [100%] (65/65 JOBS, 65 UPDATED, 65 [100.0%] CACHE MISS)
[-] TESTING...FINISHED 0.4s (2 PASS/0 FAIL)
RESULTS FOR ALL TESTS
PASS    <100ms  1 Passed   0 Skipped   0 Failed   com.vanniktech.okbuck.ExampleUnitTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed   com.vanniktech.okbuck.ExampleUnitTest
TESTS PASSED
```

**Comment by kageiit** [comment]
You are right that you dont require a special runner if you dont use robolectric. But I am able to run the tests locally. Is this something local to your machine? Maybe try it on travis?

**Comment by vanniktech** [comment]
I'm starting to believe that there's something wrong with my machine:

First of all this warning:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'files'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'files'
```

I also tried to run the project with the error reported in #335 on a coworkers machine and there Retrolambda had no issues at all.

And if that's not already enough if I try to run the test on my playground app locally I don't get any tests result.

Instead of 

```
[-] PROCESSING BUCK FILES...FINISHED 0.1s [100%] 🐳  New buck daemon
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 3.3s [100%] (65/65 JOBS, 65 UPDATED, 65 [100.0%] CACHE MISS)
[-] TESTING...FINISHED 0.4s (2 PASS/0 FAIL)
RESULTS FOR ALL TESTS
PASS    <100ms  1 Passed   0 Skipped   0 Failed   com.vanniktech.okbuck.ExampleUnitTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed   com.vanniktech.okbuck.ExampleUnitTest
TESTS PASSED
```

I get:

```
[-] PROCESSING BUCK FILES...FINISHED 0.0s 🐳  New buck daemon
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 1.6s (0/0 JOBS, 0 UPDATED)
[-] TESTING...FINISHED 0.0s
RESULTS FOR ALL TESTS
TESTS PASSED (NO TESTS RAN)
```

Is there anything with Java that needs to be set up correctly?

I've got

```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home
export JAVA8_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home
```

**Comment by vanniktech** [comment]
@kageiit [works on Travis](https://github.com/vanniktech/okbuck-playground/pull/1) thanks for the tip. Do you have any idea what could be wrong on my machine?

**Comment by kageiit** [comment]
No idea whats up on your machine. very hard to debug unfortunately :(

I cant think of anything top of my head. Ill update if i do find anything

**Comment by kageiit** [comment]
Closing this issue as it is purely local and works on travis as well. Please comment back if you do find what was different on your machine

**Comment by vanniktech** [comment]
For the record I found out why this does not work, it's because of #255. When I uninstall watchman with `brew uninstall watchman` it works and I can run my tests 🎉
