### ISSUE TITLE
Does applying the plugin override the android gradle plugin version?

### ISSUE THREAD

**Issue by Macarse** [uber/okbuck#344]
I think the android gradle plugin version is getting override in my gradle cfg by the okBuck plugin.

My app is using GreenDao and I am hitting this issue:
https://github.com/greenrobot/greenDAO/issues/498

After reading the issue, it looks like it should only happen with `com.android.tools.build:gradle:2.3.0` and I am using `com.android.tools.build:gradle:2.2.3`

I have read https://github.com/uber/okbuck/blob/master/Usage.md but there is no way of overriding the android gradle plugin version.

Any idea?

**Comment by kageiit** [comment]
You can exclude it quite easily

```
classpath('com.uber:okbuck:0.14.4') {
  exclude module: 'gradle'
}
```

Then the android gradle plugin that is picked up transitively will be replaced by whatever you include in your project explictly

**Comment by Macarse** [comment]
@kageiit If you are offering a way to override build tools might make sense to add a way to override android gradle plugin version.

**Comment by kageiit** [comment]
That's what mentioned in my comment above. It does not make sense to have an extension for this (it's not possible even). Even if it was, the android gradle plugin is not used for while running the buck build. Configuration exclude principles are a well documented gradle feature and can be used for the effect you originally desired.

**Comment by Macarse** [comment]
Just to make sure I understand correctly: You are saying that okBuck would not use the android gradle plugin?

**Comment by kageiit** [comment]
Okbuck would use the android  gradle plugin, but it cannot be overridden from an extension container. The only way to override which version it uses would be to use a dependency exclusion or substitution rule as in the comment above

**Comment by Macarse** [comment]
@kageiit thanks for answering!
