### ISSUE TITLE
Not able to make build after ./gradlew clean

### ISSUE THREAD

**Issue by gbajaj** [uber/okbuck#345]
I wanted to make a clean build, i could not find a command in buck to make clean the build folders.
I tried and` ./gradlew clean` that deleted the build folder however when I tried to make a build again using ` ./buckw build appDemoDebug` it gave the following error

**BUILD FAILED: //app:manifest_devDebug_test: parameter 'skeleton': no such file or directory 'app/build/okbuck/devDebug_test/AndroidManifest.xml'**
What is the workaround?

**Comment by kageiit** [comment]
If you want to clean fully, try

`git clean -fdx`

if using git

You can also do `./buckw clean`
