### ISSUE TITLE
Submodule dependency

### ISSUE THREAD

**Issue by vasticles** [uber/okbuck#347]
Hi!
Our app has a proprietary dependency that is maintained as a submodule. 
Whenever I try to use buck, I get an error:

./buckw targets
No build file at core/BUCK when resolving target //core:src_release.
[-] PROCESSING BUCK FILES...FINISHED 0.0s [100%]
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)

I looked at the app BUCK build file, and there are a few problematic lines scattered around:
'//core:res_main',
'//core:src_release',

The tooltip over them says "Cannot locate the Buck target".

Is my config wrong?

**Comment by kageiit** [comment]
Hmm I am not sure how you are consuming this `core` module. It needs to be added to `settings.gradle` for okbuck to generate buck files for it. Can you provide more info on your setup?

**Comment by vasticles** [comment]
This is the global `settings.gradle`:
`include ':app', ':core'
project(':core').projectDir = new File('core-repo/core')`

**Comment by kageiit** [comment]
The syntax on the second line is not supported by okbuck

See: https://github.com/uber/okbuck/issues/296

for possible workarounds

**Comment by vasticles** [comment]
Thanks for the pointer!
