### ISSUE TITLE
Some dependencies  don't resolve 

### ISSUE THREAD

**Issue by spirosoik** [uber/okbuck#356]
For example if I want to try from Nexus a specific snapshot dependency in a gradle file, okbuck doesn't really understand which jar to fetch from Nexus. Are we missing something? for example for this snapshot dependency `com.squareup.retrofit2:adapter-rxjava2`

Let me mention that this dependency belongs to an `android library module`.

It seems that in `.gradle/caches/modules-2/files` this jar is empty

If I understood correctly by my tests if we never used a library before from gradle then buck doesn't fetch the jar/sources properly.

**Comment by kageiit** [comment]
Can you post a code snippet of your gradle file? Its hard to make out much info from the ticket description

**Comment by spirosoik** [comment]
@kageiit take a look here https://gist.github.com/spirosoik/8857e626ac071007a6e391b39c454bef

**Comment by kageiit** [comment]
Check the readme closely again. You need to setup a `repositories` block for the root project build.gradle as well

```
repositories {
    jcenter()
}

apply plugin: 'com.uber.okbuck'
```
