### ISSUE TITLE
element value must be a constant expression when using ButterKnife

### ISSUE THREAD

**Issue by Macarse** [uber/okbuck#368]
Way to repro:

In a project with android modules:
 - main module using R.id.bla for ButterKnife
 - Additional modules using R2.id.bla for ButterKnife

I noticed the sample uses R2 for everything (https://github.com/uber/okbuck/blob/master/app/src/main/java/com/uber/okbuck/example/MainActivity.java#L40) changing that to use R directly fails the build.

In ButterKnife doc it says:

```
Now make sure you use R2 instead of R inside all Butter Knife annotations.
```

I can now go and replace all R for R2 in the main module but I would like to understand what's the issue. This is another setup which works in regular gradle and doesn't work in okBuck/Buck.

**Comment by kageiit** [comment]
In buck everything is built as an Android library. There is no concept of a main or library module. All libraries are then combined into a binary. This means that all code is treated like a library where R values are not final. You will have to switch to use R2 everywhere

**Comment by Macarse** [comment]
@kageiit you did the implementation for ButterKnife module support, right?
What's the reasoning behind "Now make sure you use R2 instead of R inside all Butter Knife annotations"? Is there a benefit?

I could apply the butterknife plugin to the main project but that would duplicate the ids (They would live in R and in R2) right?

Thanks

**Comment by kageiit** [comment]
The benefit is that you can build with buck :)

Duplication of ids is not a concern as `R2` s only used at build time and is replaced with R by the time the app runs.

**Comment by ankushg** [comment]
I know this issue is closed, but am I also supposed to use `R2` *outside* of ButterKnife annotations?

Buck seems to be complaining about accesses to menu ids as well, but using the `R2` identifier then triggers an error that `R2 should only be used inside annotations`...

**Comment by kageiit** [comment]
Yes you need to use if/else instead of switch case elsewhere

**Comment by sherlockHK** [comment]
axibade
