### ISSUE TITLE
Consider updating Robolectric to 3.3.1

### ISSUE THREAD

**Issue by vanniktech** [uber/okbuck#372]
Robolectrics API have changed again from `3.0.0` to `3.2.2` which means that the [BuckRobolectricTestRunner](https://github.com/uber/okbuck/blob/a607797cab9e17310a2c18326303613ad42e4858/libraries/robolectric-base/src/main/java/com/uber/okbuck/BuckRobolectricTestRunner.java) does not work anymore.

**Comment by kageiit** [comment]
Need to upstream a few changes like https://github.com/robolectric/robolectric/pull/2907 before we can tackle this

**Comment by kageiit** [comment]
https://github.com/robolectric/robolectric/releases/tag/robolectric-3.3 includes native support for the buck build system. I plan to work on it next month unless someone wants to send in a PR before :)

**Comment by vanniktech** [comment]
What would need to be done for this?

**Comment by kageiit** [comment]
RobolectricUtil needs to understand and fetch deps for version 3.3.x
the rest should work automatically

**Comment by kageiit** [comment]
This is supported in v0.20.6 . See #427 for details
