### ISSUE TITLE
Minor issue when parsing strings.xml files

### ISSUE THREAD

**Issue by Macarse** [uber/okbuck#376]
Another of those "doesn't work in okBuck but gradle doesn't care" bugs.
```
    <string name="key">value</string> 
```

Edit: sorry, I hit submit before I should.
The problem is there is an invisible character " "
 
<img width="105" alt="screen shot 2017-01-31 at 9 28 06 pm" src="https://cloud.githubusercontent.com/assets/24915/22496153/3efcc9ce-e7fc-11e6-8ffc-7c56d3789bda.png">

git diff shows the character is:
<U+2028>

**Comment by kageiit** [comment]
Do you mean it does not work with `buck`? Okbuck does not do anything special with string resource xmls.

You can delete the invisible character to make buck happy. If you belive buck should handle this case correctly, please open an issue at https://github.com/facebook/buck

**Comment by Macarse** [comment]
@kageiit Makes sense. Thanks!
