### ISSUE TITLE
Support archivesBaseName

### ISSUE THREAD

**Issue by vanniktech** [uber/okbuck#379]
It would be cool if OkBuck would support naming the built APK. In Gradle there is `archivesBaseName` for this - which would name the APK like this `app-1.0.0-release.apk`for instance.

```
android {
  defaultConfig {
    archivesBaseName = "app-$versionName"
  }
}
```

Are there any plans on supporting this one?

**Comment by kageiit** [comment]
Hmm, this can be easily achieved outside okbuck. Buck does not have any option for this.

You can do `./buckw targets <apk-target> --show-output` to get the path to the apk and you can execute a simple mv or cp to whatever you like after your build runs.

There are no plans to support naming within okbuck as it can be done fairly easily outside it.
