### ISSUE TITLE
buckw crashes if gradlew isn't found

### ISSUE THREAD

**Issue by cmelchior** [uber/okbuck#380]
We have a module structure like this:
```
examples/
  introExample/
  okbuckExample/
  gradle/
```

Each folder is their own self-contained example only sharing the minimum from the top-level folder. In particular this means sharing `gradle` and `gradlew`. If you run `:buckWrapper` from the `okBuckExample` subfolder it will work, but trying to use the wrapper from the subfolder crashes with the below error:

```
 => ./buckw targets
 NO PREVIOUS SUCCESSFUL OKBUCK RUN 
 RUNNING OKBUCK... 

 DELETED OLD BUCK FILES 
./buckw: line 144: /Users/cm/Realm/realm-java/examples/okBuckExample/gradlew: No such file or directory

 OKBUCK FAILED 
```

**Comment by kageiit** [comment]
@cmelchior It would be great if you can push a branch to your repo so we can dig deeper

**Comment by kageiit** [comment]
@cmelchior It would be great if you can push a branch to your repo so we can dig deeper

**Comment by cmelchior** [comment]
https://github.com/realm/realm-java/tree/cm/okbuck-example

```
// Checkout branch
cd examples
./gradlew okBuckExample:buckWrapper (fails)
./gradlew okBuckExample:buckWrapper (succeds)
```

**Comment by kageiit** [comment]
@cmelchior The setup seemed to be incorrect in the original branch, I have hence fixed it up and put it on https://github.com/kageiit/realm-java/commit/81197b76679b323708d152f4a53667db45ba9be2

```
cd examples
./buckw targets
```

works now. I set real versions to something released so as not have tno rebuild everything locally, but you can undo those changes

**Comment by kageiit** [comment]
@cmelchior please let me know if anything else is missing. I am going to close this ticket as there is no more action needed from okbuck's end.
