### ISSUE TITLE
buckw fails to run watchman

### ISSUE THREAD

**Issue by Piasy** [uber/okbuck#391]
When I add okbuck config below:

``` gradle
    wrapper {
        remove = ['.buckconfig.local', "**/BUCK"]
        keep = [".okbuck/**/BUCK"]
    }
```

the `getToClean` function of buckw looks like this:

``` bash
getToClean ( ) {
    ensureWatch

    watchman --output-encoding=json --no-pretty -j 2>&1 <<-EOT
["query", "$WORKING_DIR", {
    "expression": ["allof",
        ["type", "f"],
        ["anyof",
            ["name", [".buckconfig.local", "BUCK"]]
        ],
        ["not",
            ["dirname", ".okbuck"]
            ["match", ".okbuck/**/BUCK", "wholename"]
        ]
    ],
    "fields": ["name"]
}]
EOT
}
```

There are two problems:

1. in the `not` expression, the json syntax is invalid, a comma is missing, so watchman fails with `failed to parse command from stdin: ']' expected near '['`;
2. after adding a comma, watchman fails with `{"version":"4.7.0","error":"failed to parse query: must use [\"not\", expr]"}`;

The reason is that I add the `keep = [".okbuck/**/BUCK"]` in okbuck config, and I create a [reproduce project here](https://github.com/OkBuilds/BuckwWatchmanErrorReproduce).

**Comment by kageiit** [comment]
@Piasy you do not need to add `["match", ".okbuck/**/BUCK", "wholename"]` i.e you dont need to add a keep entry separately anymore as `["dirname", ".okbuck"]` covers everything inside `.okbuck` already

**Comment by kageiit** [comment]
That said, I put up a fix in #392 for anyone configuring to keep files outside `.okbuck`. But if you just care about `BUCK` files inside `.okbuck`, you should not override the `keep` argument as the watchman query gets more verbose unnecessarily.

**Comment by Piasy** [comment]
Yeah, I think it's nice to update the Usage.md too, it still contains that configuration.

**Comment by kageiit** [comment]
Updated usage.md
