### ISSUE TITLE
Possible ordering issue in merging main and flavor resources

### ISSUE THREAD

**Issue by ChaitanyaPramod** [uber/okbuck#393]
We had a file (adapter.xml) defining "account_type" string in main/res/values, and also another file (adapter.xml) defining "account_type" string in debug/res/values.
The debug APK built by Gradle contains the correct debug string value, but the OkBuck built debug APK contains the prod value for the string.

As a work-around, I had to move this file from main/res/values to prod/res/values so that the wrong string value isn't picked.

Expected behavior: flavor resources override main resources.

This issue could have some relation with #361.

Edit, additional info:
OkBuck version 0.17.0
buck version https://github.com/facebook/buck/commit/3319cd6ce5c0126fea859932cc5c2494e95b63b9

**Comment by kageiit** [comment]
The ordering is not possible to infer in okbuck. The recommended approach is not not set a value in main but just set a value in `debug` and `release` (or `prod` in your case) separately. Okbuck/buck only support resource values that can refer to each other in the various main/buildType/flavor resource folders.

Overriding main resources is not supported and will likely never will be as it incurs a significant overhead at okbuck time and also creates difficult situations with how the `android_resource` rules must be laid out for such cases.
