### ISSUE TITLE
Android resource error

### ISSUE THREAD

**Issue by adauvalter** [uber/okbuck#397]
After starting with ./buckw test. I'm facing the following problem:

`BUILD FAILED: //app:res_debug: parameter 'res': cannot coerce '{anim/slide_from_left.xml=src/main/res/anim/slide_from_left.xml, anim/slide_from_right.xml=src/main/res/anim/slide_from_right.xml, anim/slide_to_bottom.xml=src/main/res/anim/slide_to_bottom.xml, anim/slide_to_left.xml=src/main/res/anim/slide_to_left.xml, anim/slide_to_right.xml=src/main/res/anim/slide_to_right.xml, anim/slide_to_top.xml=src/main/res/anim/slide_to_top.xml, anim/stay.xml=src/main/res/anim/stay.xml, drawable-hdpi/co_logo_s.png=src/main/res/drawable-hdpi/co_logo_s.png, drawable-hdpi/ic_file_pdf.png=src/main/res/drawable-hdpi/ic_file_pdf.png, drawable-hdpi/ic_file_powerpoint.png=src/main/res/drawable-hdpi/ic_file_powerpoint.png, drawable-hdpi/ic_file_txt.png=src/main/res/drawable-hdpi/ic_file_txt.png, drawable-hdpi/ic_file_word.png=src/main/res/drawable-hdpi/ic_file_word.png, drawable-mdpi/co_logo_s.png=src/main/res/drawable-mdpi/co_logo_s.png, drawable-mdpi/ic_file_pdf.png=src/main/res/drawable-mdpi/ic_file_pdf.png, drawable-mdpi/ic_file_powerpoint.png=src/main/res/drawable-mdpi/ic_file_powerpoint.png, drawable-mdpi/ic_file_txt.png=src/main/res/drawable-mdpi/ic_file_txt.png, drawable-mdpi/ic_file_word.png=src/main/res/drawable-mdpi/ic_file_word.png, drawable-xhdpi/co_logo_s.png=src/main/res/drawable-xhdpi/co_logo_s.png, drawable-xhdpi/ic_file_pdf.png=src/main/res/drawable-xhdpi/ic_file_pdf.png, drawable-xhdpi/ic_file_powerpoint.png=src/main/res/drawable-xhdpi/ic_file_powerpoint.png, drawable-xhdpi/ic_file_txt.png=src/main/res/drawable-xhdpi/ic_file_txt.png, drawable-xhdpi/ic_file_word.png=src/main/res/drawable-xhdpi/ic_file_word.png, drawable-xxhdpi/co_logo_s.png=src/main/res/drawable-xxhdpi/co_logo_s.png, drawable-xxhdpi/ic_file_pdf.png=src/main/res/drawable-xxhdpi/ic_file_pdf.png, drawable-xxhdpi/ic_file_powerpoint.png=src/main/res/drawable-xxhdpi/ic_file_powerpoint.png, drawable-xxhdpi/ic_file_txt.png=src/main/res/drawable-xxhdpi/ic_file_txt.png, drawable-xxhdpi/ic_file_word.png=src/main/res/drawable-xxhdpi/ic_file_word.png, drawable-xxxhdpi/co_logo_s.png=src/main/res/drawable-xxxhdpi/co_logo_s.png, drawable-xxxhdpi/ic_drop_shadow_bottom.9.png=src/main/res/drawable-xxxhdpi/ic_drop_shadow_bottom.9.png, drawable-xxxhdpi/ic_drop_shadow_top.9.png=src/main/res/drawable-xxxhdpi/ic_drop_shadow_top.9.png, drawable-xxxhdpi/ic_file_pdf.png=src/main/res/drawable-xxxhdpi/ic_file_pdf.png, drawable-xxxhdpi/ic_file_powerpoint.png=src/main/res/drawable-xxxhdpi/ic_file_powerpoint.png, drawable-xxxhdpi/ic_file_txt.png=src/main/res/drawable-xxxhdpi/ic_file_txt.png, drawable-xxxhdpi/ic_file_word.png=src/main/res/drawable-xxxhdpi/ic_file_word.png, drawable/group_avatar.xml=src/main/res/drawable/group_avatar.xml, drawable/ic_add_white.xml=src/main/res/drawable/ic_add_white.xml, drawable/ic_arrow_back_gray.xml=src/main/res/drawable/ic_arrow_back_gray.xml, drawable/ic_arrow_back_white.xml=src/main/res/drawable/ic_arrow_back_white.xml, drawable/ic_call.xml=src/main/res/drawable/ic_call.xml, drawable/ic_chat.xml=src/main/res/drawable/ic_chat.xml, drawable/ic_check_grey.xml=src/main/res/drawable/ic_check_grey.xml, drawable/ic_close_white.xml=src/main/res/drawable/ic_close_white.xml, drawable/ic_doublecheck.xml=src/main/res/drawable/ic_doublecheck.xml, drawable/ic_mail.xml=src/main/res/drawable/ic_mail.xml, drawable/ic_new_group_close.xml=src/main/res/drawable/ic_new_group_close.xml, drawable/ic_search.xml=src/main/res/drawable/ic_search.xml, drawable/ic_tab_chat.xml=src/main/res/drawable/ic_tab_chat.xml, drawable/ic_tab_contacts.xml=src/main/res/drawable/ic_tab_contacts.xml, drawable/illu_empty_chat.xml=src/main/res/drawable/illu_empty_chat.xml, drawable/round_fill_image_view.xml=src/main/res/drawable/round_fill_image_view.xml, drawable/view_avatar_online_primary_stroke.xml=src/main/res/drawable/view_avatar_online_primary_stroke.xml, drawable/view_avatar_online_white_stroke.xml=src/main/res/drawable/view_avatar_online_white_stroke.xml, drawable/view_badge_shape.xml=src/main/res/drawable/view_badge_shape.xml, drawable/white_cursor.xml=src/main/res/drawable/white_cursor.xml, layout/activity_channel.xml=src/main/res/layout/activity_channel.xml, layout/activity_channel_group_details.xml=src/main/res/layout/activity_channel_group_details.xml, layout/activity_channel_single_details.xml=src/main/res/layout/activity_channel_single_details.xml, layout/activity_contact_details.xml=src/main/res/layout/activity_contact_details.xml, layout/activity_create_channel.xml=src/main/res/layout/activity_create_channel.xml, layout/activity_create_channel_group.xml=src/main/res/layout/activity_create_channel_group.xml, layout/activity_group_name.xml=src/main/res/layout/activity_group_name.xml, layout/activity_home.xml=src/main/res/layout/activity_home.xml, layout/activity_onboard.xml=src/main/res/layout/activity_onboard.xml, layout/pager_onboarding_page_0.xml=src/main/res/layout/pager_onboarding_page_0.xml, layout/pager_onboarding_page_1.xml=src/main/res/layout/pager_onboarding_page_1.xml, layout/pager_onboarding_page_2.xml=src/main/res/layout/pager_onboarding_page_2.xml, layout/view_attachment_all.xml=src/main/res/layout/view_attachment_all.xml, layout/view_attachment_item.xml=src/main/res/layout/view_attachment_item.xml, layout/view_avatar.xml=src/main/res/layout/view_avatar.xml, layout/view_badge_icon.xml=src/main/res/layout/view_badge_icon.xml, layout/view_channel_item.xml=src/main/res/layout/view_channel_item.xml, layout/view_contact.xml=src/main/res/layout/view_contact.xml, layout/view_contact_details_action_icon.xml=src/main/res/layout/view_contact_details_action_icon.xml, layout/view_contact_details_header.xml=src/main/res/layout/view_contact_details_header.xml, layout/view_contact_entity.xml=src/main/res/layout/view_contact_entity.xml, layout/view_contact_item_with_char.xml=src/main/res/layout/view_contact_item_with_char.xml, layout/view_contact_unlickable_without_status.xml=src/main/res/layout/view_contact_unlickable_without_status.xml, layout/view_contact_with_role.xml=src/main/res/layout/view_contact_with_role.xml, layout/view_contact_without_char_item.xml=src/main/res/layout/view_contact_without_char_item.xml, layout/view_create_group_chat_chosen_item.xml=src/main/res/layout/view_create_group_chat_chosen_item.xml, layout/view_search_text_item.xml=src/main/res/layout/view_search_text_item.xml, layout/view_search_toolbar.xml=src/main/res/layout/view_search_toolbar.xml, layout/view_text_entry.xml=src/main/res/layout/view_text_entry.xml, menu/menu_create_channel.xml=src/main/res/menu/menu_create_channel.xml, menu/menu_create_group.xml=src/main/res/menu/menu_create_group.xml, menu/menu_group_name.xml=src/main/res/menu/menu_group_name.xml, menu/menu_main.xml=src/main/res/menu/menu_main.xml, mipmap-hdpi/ic_launcher.png=src/main/res/mipmap-hdpi/ic_launcher.png, mipmap-mdpi/ic_launcher.png=src/main/res/mipmap-mdpi/ic_launcher.png, mipmap-xhdpi/ic_launcher.png=src/main/res/mipmap-xhdpi/ic_launcher.png, mipmap-xxhdpi/ic_launcher.png=src/main/res/mipmap-xxhdpi/ic_launcher.png, mipmap-xxxhdpi/ic_launcher.png=src/main/res/mipmap-xxxhdpi/ic_launcher.png, values-en/phraseapp.xml=src/main/res/values-en/phraseapp.xml, values/attrs.xml=src/main/res/values/attrs.xml, values/colors.xml=src/main/res/values/colors.xml, values/config.xml=src/main/res/values/config.xml, values/dimens.xml=src/main/res/values/dimens.xml, values/phraseapp.xml=src/main/res/values/phraseapp.xml, values/styles.xml=src/main/res/values/styles.xml, values/themes.xml=src/main/res/values/themes.xml}' to interface java.nio.file.Path`

**Comment by kageiit** [comment]
See #399
