### ISSUE TITLE
Okbuck Fails to build drawable-xxx in R.java

### ISSUE THREAD

**Issue by kuldeeptomer** [uber/okbuck#398]
Error Log:

/Users/kuldeep.tomer/Documents/Druid/buck-out/bin/app/__src_devDebug#dummy_r_dot_java_rdotjava_src__/com/aranoah/healthkart/plus/R.java:1844: error: ';' expected
    public static int drawable-hdpi=0x07f045b0;
                              ^
/Users/kuldeep.tomer/Documents/Druid/buck-out/bin/app/__src_devDebug#dummy_r_dot_java_rdotjava_src__/com/aranoah/healthkart/plus/R.java:1844: error: <identifier> expected
    public static int drawable-hdpi=0x07f045b0;
                                   ^
/Users/kuldeep.tomer/Documents/Druid/buck-out/bin/app/__src_devDebug#dummy_r_dot_java_rdotjava_src__/com/aranoah/healthkart/plus/R.java:1845: error: ';' expected
    public static int drawable-mdpi=0x07f045b1;
                              ^
/Users/kuldeep.tomer/Documents/Druid/buck-out/bin/app/__src_devDebug#dummy_r_dot_java_rdotjava_src__/com/aranoah/healthkart/plus/R.java:1845: error: <identifier> expected
    public static int drawable-mdpi=0x07f045b1;
                                   ^
/Users/kuldeep.tomer/Documents/Druid/buck-out/bin/app/__src_devDebug#dummy_r_dot_java_rdotjava_src__/com/aranoah/healthkart/plus/R.java:1846: error: ';' expected
    public static int drawable-xhdpi=0x07f045b2;
                              ^
/Users/kuldeep.tomer/Documents/Druid/buck-out/bin/app/__src_devDebug#dummy_r_dot_java_rdotjava_src__/com/aranoah/healthkart/plus/R.java:1846: error: <identifier> expected
    public static int drawable-xhdpi=0x07f045b2;
                                    ^
/Users/kuldeep.tomer/Documents/Druid/buck-out/bin/app/__src_devDebug#dummy_r_dot_java_rdotjava_src__/com/aranoah/healthkart/plus/R.java:1847: error: ';' expected
    public static int drawable-xxhdpi=0x07f045b3;
                              ^
/Users/kuldeep.tomer/Documents/Druid/buck-out/bin/app/__src_devDebug#dummy_r_dot_java_rdotjava_src__/com/aranoah/healthkart/plus/R.java:1847: error: <identifier> expected
    public static int drawable-xxhdpi=0x07f045b3;
                                     ^
/Users/kuldeep.tomer/Documents/Druid/buck-out/bin/app/__src_devDebug#dummy_r_dot_java_rdotjava_src__/com/aranoah/healthkart/plus/R.java:1848: error: ';' expected
    public static int drawable-xxxhdpi=0x07f045b4;
Errors: 10. Warnings: 0.

BUILD FAILED: //app:bin_devDebug#aapt_package failed with exit code 1:

                              ^

**Comment by kageiit** [comment]
Which version of buck are you on? Can you consider updating to latest as detailed in #399

**Comment by kuldeeptomer** [comment]
I have configured head commit hash from Buck master in my .buckversion
