### ISSUE TITLE
dimen values

### ISSUE THREAD

**Issue by Yuliya-Kaleda** [uber/okbuck#402]
Seems like there is an issue pulling dimen values:

`buck-out/gen/baselib/res_stagingDebug#resources-symlink-tree/res/layout/view_ship_config_info.xml:11: error: Error: No resource found that matches the given name (at 'padding' with value '@dimen/ship_config_info_padding').`

`buck-out/gen/pdplib/res_stagingDebug#resources-symlink-tree/res/layout/view_details_top_content.xml:22: error: Error: No resource found that matches the given name (at 'layout_marginLeft' with value '@dimen/pdv_horizontal_margin').`

Okbuck 0.17.3

**Comment by kageiit** [comment]
Could be related to #393 . If so, check the workaround in that issue

**Comment by Yuliya-Kaleda** [comment]
I don't think it is the same issue. All value resources  are located in main/. There are no dimens resources in flavour packages. Strings, colors, styles are found with no issues, while dimens are not.

**Comment by kageiit** [comment]
You should file this issue with buck and include a small sample project. Since the failure is in buck level, there is not much we can do from the okbuck side.
