### ISSUE TITLE
Too many field references: 65874; max is 65536. Too many classes to fit in one dex file.

### ISSUE THREAD

**Issue by sabergeek** [uber/okbuck#405]
Hi there,

I've been stuck at trying to get OkBuck working and thought of seeking help now. The project i'm working on has multiple modules and exceeds 64k methods (our project sums to around 65k). Multidex is enabled in gradle and i've also added the following code before executing _./gradlew build app:bin_betaDebug_

```
okbuck {
    linearAllocHardLimit = [
            app: 70000
    ]
primaryDexPatterns = [
            app: [
                    '^com.project.client.MainApplication^'
            ]
    ]

```
Despite extending the limit to 70000 (which has also reflected in the BUCK file), building with buck still reports the 64k limit and is seemingly not picking up the new limit.

I'm on `OkBuck 0.18.0`

I've tried adding _trim_resource_ids = True_ in the binary rule in the BUCK file as suggested at https://github.com/facebook/buck/issues/926 but the too many field references error is persistent with the reported 64k limit.

> BUILD FAILED: //app:bin_betaDebug#dex_uber_r_dot_java failed with exit code 2:
> dx

I've tried rebuilding the project with the gradle wrapper, then cleaning the buck generated files too. Is there anything I could be missing? 

Let me know any other information you may need.

Thanks!

**Comment by kageiit** [comment]
Can you tell me how you are setting `trim_resource_ids = True` in the generated buck file?

**Comment by sabergeek** [comment]
I've made the entry within android_binary -

```
android_binary(
	name = 'bin_productionRelease',
	manifest = ':manifest_productionRelease',
	keystore = '//.okbuck/keystore/app:key_store_productionRelease.keystore',
	**use_split_dex = True,**
	linear_alloc_hard_limit = 7194304,
	primary_dex_patterns = [
		'^com/project/client/MainApplication^'
	],
	manifest_entries = {
		'placeholders': {
			'applicationId': 'com.project.client',
		},
	},
	deps = [
		':res_productionRelease',
		':src_productionRelease',
	],
	visibility = [
		'PUBLIC',
	],
)
```

**Comment by sabergeek** [comment]
@kageiit Yikes. OkBuck is fine! It was an error from my end. I overlooked the existence of multiple android_binary entries. After adding _trim_resource_ids = True_  to the correct android_binary block (which is the flavor I was interested in installing), it all went well! :smiley:
