### ISSUE TITLE
Symlinks to first party Android Support Lib sources jars are incorrect

### ISSUE THREAD

**Issue by seanabraham** [uber/okbuck#407]
I noticed the following rulekey mismatch when doing diffing builds between two machines (via https://github.com/facebook/buck/blob/master/scripts/diff_rulekeys.py):

```
Change details for [//.okbuck/cache:com.android.support.support-annotations-25.1.1.jar]
  (sourceJar):
    -[path(.okbuck/cache/com.android.support.support-annotations-25.1.1-sources.jar:2755428e38920b7ae320133ee05326c257bc3550)]
    +[path(.okbuck/cache/com.android.support.support-annotations-25.1.1-sources.jar:b9dd47d1f82390ba0a5dc77d85a9ab3598f14b21)]
```

This was quite confusing and I looked into the okbuck-generated symlinks which yielded the following:

```
$ ls -ld *support-annotations*
lrwxr-xr-x 1 sean_abraham staff 145 Feb 17 12:02 com.android.support.support-annotations-25.1.1-sources.jar -> /Users/sean_abraham/android-sdk/extras/android/m2repository/com/android/support/support-annotations/19.1.0/support-annotations-19.1.0-sources.jar
lrwxr-xr-x 1 sean_abraham staff 137 Feb 17 12:02 com.android.support.support-annotations-25.1.1.jar -> /Users/sean_abraham/android-sdk/extras/android/m2repository/com/android/support/support-annotations/25.1.1/support-annotations-25.1.1.jar
```

Upon further inspection, it appears that of all the jars in the `.okbuck/cache` folder only sources jars from the first party android support library symlink to incorrect versions. This is harmful because, as `source_jar`s are part of the `RuleKey` calculation for the `prebuilt_jar` rule, the incorrect symlinking and differences between machines cause caching to break.

cc @kageiit

**Comment by seanabraham** [comment]
If I had to guess, I'd say this could be the cause: https://github.com/uber/okbuck/commit/8edb484686ac3f444bb1ab145bad4b95ecd478fd

**Comment by seanabraham** [comment]
This is also probably related https://github.com/uber/okbuck/commit/8edb484686ac3f444bb1ab145bad4b95ecd478fd#diff-c032ac5677e6122f29974019b7d3cdc4R198

The directory tree for first party android dependencies looks like:
```
$ tree
.
├── 19.1.0
│   ├── support-annotations-19.1.0-javadoc.jar
│   ├── support-annotations-19.1.0-javadoc.jar.md5
│   ├── support-annotations-19.1.0-javadoc.jar.sha1
│   ├── support-annotations-19.1.0-sources.jar
│   ├── support-annotations-19.1.0-sources.jar.md5
│   ├── support-annotations-19.1.0-sources.jar.sha1
│   ├── support-annotations-19.1.0.jar
│   ├── support-annotations-19.1.0.jar.md5
│   ├── support-annotations-19.1.0.jar.sha1
│   ├── support-annotations-19.1.0.pom
│   ├── support-annotations-19.1.0.pom.md5
│   └── support-annotations-19.1.0.pom.sha1
├── 20.0.0
│   ├── support-annotations-20.0.0-javadoc.jar
│   ├── support-annotations-20.0.0-javadoc.jar.md5
│   ├── support-annotations-20.0.0-javadoc.jar.sha1
│   ├── support-annotations-20.0.0-sources.jar
│   ├── support-annotations-20.0.0-sources.jar.md5
│   ├── support-annotations-20.0.0-sources.jar.sha1
│   ├── support-annotations-20.0.0.jar
│   ├── support-annotations-20.0.0.jar.md5
│   ├── support-annotations-20.0.0.jar.sha1
│   ├── support-annotations-20.0.0.pom
│   ├── support-annotations-20.0.0.pom.md5
│   └── support-annotations-20.0.0.pom.sha1
├── 21.0.0
│   ├── support-annotations-21.0.0-javadoc.jar
│   ├── support-annotations-21.0.0-javadoc.jar.md5
│   ├── support-annotations-21.0.0-javadoc.jar.sha1
│   ├── support-annotations-21.0.0-sources.jar
│   ├── support-annotations-21.0.0-sources.jar.md5
│   ├── support-annotations-21.0.0-sources.jar.sha1
│   ├── support-annotations-21.0.0.jar
│   ├── support-annotations-21.0.0.jar.md5
│   ├── support-annotations-21.0.0.jar.sha1
│   ├── support-annotations-21.0.0.pom
│   ├── support-annotations-21.0.0.pom.md5
│   └── support-annotations-21.0.0.pom.sha1
...
```

Whereas the directory tree in the gradle cache looks like:
```
├── 4.0
│   ├── 4a33d6206d6d442446a8edbd2b0798ecfaebc229
│   │   └── asm-util-4.0-sources.jar
│   ├── d7a65f54cda284f9706a750c23d64830bb740c39
│   │   └── asm-util-4.0.jar
│   └── f7bc75f7ed3f2201899bd6fcb53c61cac24baa30
│       └── asm-util-4.0.pom
├── 4.1
│   ├── 4354806dc63ac686ae4cec20192d437e9701dfb5
│   │   └── asm-util-4.1.pom
│   └── 6344065cb0f94e2b930a95e6656e040ebc11df08
│       └── asm-util-4.1.jar
└── 5.0.1
    ├── 78ebb2694324283f3120aa3ed52465b22fab8a4a
    │   └── asm-util-5.0.1-sources.jar
    ├── 7c8caddfbd0b2d7b844f8fcc75175b9cb9cf4724
    │   └── asm-util-5.0.1.jar
    └── e1f6ce1367f27bcf6add9e28cc65ad8827e2fdb
        └── asm-util-5.0.1.pom
```

So for android dependencies, sources jars share the same parent as the main jar whereas for gradle dependencies, the sources jar and main jar, only share their parent's parent (hence the `dependency.depFile.parentFile.parentFile.absolutePath` in the linked linked.

**Comment by seanabraham** [comment]
I confirmed that reverting https://github.com/uber/okbuck/commit/8edb484686ac3f444bb1ab145bad4b95ecd478fd fixes the problem, after deleting the `.okbuck/cache` and re-running okbuck. What was the reason for the change @kageiit?

**Comment by kageiit** [comment]
Trying to remember why exactly. Nothing comes to mind immediately. Probably just a simplification. Will look into reverting it

@raviagarwal7 do you remember why we did this?

**Comment by raviagarwal7** [comment]
I think this was changed as sources jar is not always named `<actual-jar/aar-prefix>-source.jar`.
an example is I found:
<img width="311" alt="screen shot 2017-03-04 at 2 51 49 am" src="https://cloud.githubusercontent.com/assets/1913956/23578178/b7f6e5b6-0085-11e7-976d-929fc831a248.png">

I think we need to change the lookup to be something like `<actual-jar/aar-prefix>.*<-sources.jar>` to cover all scenarios. Also assert that sourceJars size is less than 2.

**Comment by seanabraham** [comment]
@raviagarwal7 how do you decide what the prefix is? Start of the string up through the version?

**Comment by kageiit** [comment]
@seanabraham thanks for the report. The revert is done in 7c6e155dd7e3cec99fe11e5603ba90c5cc290280 and should fix this issue.

**Comment by seanabraham** [comment]
Thanks @kageiit, this solution looks fine for my purposes although I am worried that it wouldn't fix the situation @raviagarwal7 posted. I'm not sure how common that is though (and it's better to miss source jars than to include the wrong ones so the change is at least a step in the right direction)

**Comment by kageiit** [comment]
Ya thats what we discussed and agreed upon. If its a bad naming scheme on the jar side, we just do not include sources as such instances are quite uncommon
