### ISSUE TITLE
Must set ANDROID_SDK to point to the absolute path of your Android SDK directory

### ISSUE THREAD

**Issue by guptasourabh** [uber/okbuck#412]
Getting this error , even after correctly setting the path.

<img width="1072" alt="screen shot 2017-03-20 at 9 07 41 pm" src="https://cloud.githubusercontent.com/assets/4599610/24107687/71f51554-0db1-11e7-9dfa-eca86f576c97.png">

@kageiit  Any idea ?

**Comment by kageiit** [comment]
Can you try setting `ANDROID_HOME` instead?

**Comment by guptasourabh** [comment]
Still the same issue
<img width="1249" alt="screen shot 2017-03-20 at 11 08 59 pm" src="https://cloud.githubusercontent.com/assets/4599610/24113268/41a563de-0dc2-11e7-9273-3932f9606cf4.png">

**Comment by kageiit** [comment]
This seems like a buck issue. Can you please open a ticket on the buck ticket tracker on github? okbuck cannot do much in this regard.
