### ISSUE TITLE
 Cannot get property 'abiFilters' on null object

### ISSUE THREAD

**Issue by ceozhu** [uber/okbuck#413]
When I run command: ./buckw targets

it's wrong with that

**Comment by kageiit** [comment]
I am not sure I understand the question. Can you give an example build.gradle? a stacktrace?

**Comment by ceozhu** [comment]
//app/build.gradle:
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "care.www.skinrun.com.buckbuildexam"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags ""
            }
        }


    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.1'
    compile 'com.android.support:design:25.2.0'
    testCompile 'junit:junit:4.12'
}

**Comment by ceozhu** [comment]
more info 

MacBook-Pro:BuckBuildExam zhupei$ ./buckw targets
 CHANGES DETECTED IN: 
app/build.gradle

 RUNNING OKBUCK... 

Parallel execution with configuration on demand is an incubating feature.
Observed package id 'build-tools;20.0.0' in inconsistent location '/Users/zhupei/Documents/adt-bundle-mac-x86_64-20140702/sdk/android-4.4W' (Expected '/Users/zhupei/Documents/adt-bundle-mac-x86_64-20140702/sdk/build-tools/20.0.0')
Observed package id 'build-tools;19.0.0' in inconsistent location '/Users/zhupei/Documents/adt-bundle-mac-x86_64-20140702/sdk/build-tools/build-tools-19.0.0' (Expected '/Users/zhupei/Documents/adt-bundle-mac-x86_64-20140702/sdk/build-tools/19.0.0')
Incremental java compilation is an incubating feature.
:setupOkbuck FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':setupOkbuck'.
> Cannot get property 'abiFilters' on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.344 secs

 OKBUCK FAILED 

MacBook-Pro:BuckBuildExam zhupei$

**Comment by kageiit** [comment]
okbuck does not support `externalNativeBuild` . That seems to be your issue

**Comment by ceozhu** [comment]
appreciated u echo,I remove the func of externalNativeBuild  it's working ,thanks
