### ISSUE TITLE
DexGuard integration?

### ISSUE THREAD

**Issue by tfKamran** [uber/okbuck#418]
I have been using DexGuard successfully with `Gradle` in Android Studio without any issues. I recently tried my hands on `OkBuck` to speed up my build time and it really helped me.

Although it is able to build debug and signed APKs for me, but when I try building for release with DexGuard like:

    ./buckw install --run app:bin_release

I get the following error:

    Error: Unknown option '-dalvik' in line 9 of file 'SomeApp/app/build/okbuck/release/proguard.pro',
      included from line 60 of file 'buck-out/gen/app/bin_release/proguard/command-line.txt',
      included from argument number 1

    BUILD FAILED: //app:bin_release failed with exit code 1:
    proguard_obfuscation
    stderr: Error: Unknown option '-dalvik' in line 9 of file 'SomeApp/app/build/okbuck/release/proguard.pro',
      included from line 60 of file 'buck-out/gen/app/bin_release/proguard/command-line.txt',
      included from argument number 1

---

It is probably insignificant to mention the details of DexGuard integration as it is done as per the documentation and is working fine when I build from within Android Studio or using `./gradlew`, but here it is:

SomeApp/build.gradle:

    buildscript {
        ext {
            DEXGUARD_HOME = "$System.env.DEXGUARD_HOME"
        }

    ...    

SomeApp/app/build.gradle:

    buildTypes {
        ...

        release {
             minifyEnabled true
             proguardFile DEXGUARD_HOME + "Dexguard-7.3.11/lib/dexguard-release-aggressive.pro"
             proguardFile 'dexguard-project.txt'
             signingConfig signingConfigs.release
         }
    }

Refer this thread on StackOverflow for more information: [Buck/OkBuck: DexGuard integration not working](http://stackoverflow.com/questions/43184314/buck-okbuck-dexguard-integration-not-working)

**Comment by kageiit** [comment]
This is actually quite easy to do. Dexguard is a drop in replacement for proguard. You should be able to tweak your `.buckconfig` to point buck to the dexguard file - https://buckbuild.com/concept/buckconfig.html#tools.proguard and it should work as expected.

This is not really something to fix in okbuck.

**Comment by ajans** [comment]
No, pointing to the dexguard-jar in .buckconfig.local and .buckconfig doesn't change anything about the built apk.
The build.gradle is using DexGuard like it is referenced in their documentation.
In app/build.gradle:

```
apply plugin: 'com.android.application'
apply plugin: 'dexguard'

...

        release {
            proguardFile getDefaultDexGuardFile('dexguard-release.pro')
            proguardFile 'dexguard-project-release.txt'
            proguardFile 'dexguard-project-release-remove-logging.txt'
            proguardFile 'proguard-project.txt'
            signingConfig signingConfigs.releaseConfigPlayStore
        }
```



In .buckconfig(.local):

```
[tools]
        proguard = DexGuard/lib/dexguard.jar
```

Nothing is obfuscated, not even a hint at executing dexguard.
I'm guessing I am either setting the wrong path to the dexguard.jar (is it meant to be relative to the project-dir?), or okbuck is not able to interpret the method `getDefaultDexGuardFile` in the app/build.gradle. But then it should at least apply the other proguard-compatible rules.
