### ISSUE TITLE
OkBuck and Android Studio

### ISSUE THREAD

**Issue by kokeroulis** [uber/okbuck#428]
Hello,

First of all thank you for creating this awesome project.

I have successfully setup my project with okbuck, it builds and installs perfectly. I can see my main activity. So after that i run ./buckw project and i opened it with Android studio. The Android studio does see everything as it should be. For example the resources (drawable, layouts etc) are being shown as folders instead of being categorised.  From my main activity i cannot open the main activity layout with cmd + click. Also in my project i am using annotation processors like autovalue and dagger.
But the AS doesn't see the generated classes.

Should i do anything extra?

My project is a work project so i cannot provide you with the source code in order to take a look at it, but i can give you logs, contents of the build.gradle files etc.

**Comment by kokeroulis** [comment]
Hello again,

I was able to "reproduce" the above with this repository.
AS is complaining that the imported project doesn't use gradle as a build (same applies to my project).

Here is the steps to reproduce it

1. clean the project
2. build the demo app
3. generate the "project" file
4. open the project with AS

![migrade to gradle](https://cloud.githubusercontent.com/assets/470064/25305886/21f15cb2-278c-11e7-9cbd-78d797bcfa7e.png)
![as content](https://cloud.githubusercontent.com/assets/470064/25305887/2225c86c-278c-11e7-9865-8ddc476b15b6.png)

[generate_project.txt](https://github.com/uber/okbuck/files/949096/generate_project.txt)
[build_demo_app.txt](https://github.com/uber/okbuck/files/949098/build_demo_app.txt)
[clean_project_and_reconfigure.txt](https://github.com/uber/okbuck/files/949097/clean_project_and_reconfigure.txt)

**Comment by kageiit** [comment]
We do not recommend using AS with buck generated projects. We recommend you use intellij instead to open the project.

**Comment by kageiit** [comment]
Please comment if anything is not working with intellij. We do not recommend using Studio with buck generated projects.

**Comment by kokeroulis** [comment]
HI,

With intellij everything works as expected
