### ISSUE TITLE
Running okbuck tasks without the wrapper leads to inconsistent builds.

### ISSUE THREAD

**Issue by runningcode** [uber/okbuck#429]
Running `./gradlew okbuck` or `./gradlew okbuckclean` without the buck wrapper can put your project in an incorrect state.

Example: if your build gets in a weird state and you run `./gradlew okbuckclean` to try to fix it, your project could end up in a worse state because the okbuck task is invoked without the `-Dokbuck.wrapper=true`argument like it normally set in the buck wrapper.

How can one run `./gradlew okbuckclean` without screwing up the build?

**Comment by kageiit** [comment]
`git clean -fdx` to clean everything.

You should not need to run `./gradlew okbuck` by itself. It is not recommended anywhere in the README or wiki (should remove it if it is) and all interaction has to flow through `buckw`.

If you really want to invoke `./gradlew okbuckClean` separately, you can add the wrapper system prop or modify your `buckw` to call it internally when calling clean
