### ISSUE TITLE
`brew install android-ndk` no longer works.

### ISSUE THREAD

**Issue by KevCron** [uber/okbuck#434]
I get the following when running `brew install android-ndk`:

<img width="616" alt="screen shot 2017-04-27 at 7 17 30 pm" src="https://cloud.githubusercontent.com/assets/9090280/25508166/37bca3da-2b7e-11e7-9b2a-812c64566079.png">

However running `brew cask install android-ndk` works fine. I'll be submitting a PR to fix the README shortly.

**Comment by kageiit** [comment]
Do not bother. See #421 :)

**Comment by KevCron** [comment]
Ah, my apologies, I should have looked at the PRs to see if this was already resolved.

**Comment by kageiit** [comment]
Instructions updated at - https://github.com/uber/okbuck#installation

Thanks!
