### ISSUE TITLE
Could not resolve all artifacts for configuration ':proguardDepCache'.

### ISSUE THREAD

**Issue by guhan121** [uber/okbuck#465]
in our project;

we modify the
in project root path 

in "gradle.properties" file :
proguard_version=5.3.2.M.0.0.8
 
in "build.gradle" file
     configurations.all {
        resolutionStrategy {
            force "net.sf.proguard:proguard-gradle:${proguard_version}"
        }
    }

when i run 
"./buckw targets --stacktrace"

I got

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':okbuck'.
> Could not resolve all artifacts for configuration ':proguardDepCache'.
   > Could not find net.sf.proguard:proguard-base:.
     Searched in the following locations:
         http://127.0.0.10:8181/nexus/content/groups/public/net/sf/proguard/proguard-base//proguard-base-.pom
         http://127.0.0.10:8181/nexus/content/groups/public/net/sf/proguard/proguard-base//proguard-base-.jar
         file:/home/user/android-sdk-linux/extras/android/m2repository/net/sf/proguard/proguard-base//proguard-base-.pom
         file:/home/user/android-sdk-linux/extras/android/m2repository/net/sf/proguard/proguard-base//proguard-base-.jar
         file:/home/user/android-sdk-linux/extras/google/m2repository/net/sf/proguard/proguard-base//proguard-base-.pom
         file:/home/user/android-sdk-linux/extras/google/m2repository/net/sf/proguard/proguard-base//proguard-base-.jar
         file:/home/user/android-sdk-linux/extras/m2repository/net/sf/proguard/proguard-base//proguard-base-.pom
         file:/home/user/android-sdk-linux/extras/m2repository/net/sf/proguard/proguard-base//proguard-base-.jar
     Required by:
         project :

why okbuck not get version for proguard-base?

but our modified proguard-gradle integrated proguard-base,we not need  proguard-base.

**Comment by kageiit** [comment]
You need to put `"net.sf.proguard:proguard-gradle:${proguard_version}"` as a classpath dependency because that is where okbuck looks to bring in the dependency.

Also, `configurations.all` does not apply to the buildScript dependencies which is why you are seeing the error
