### ISSUE TITLE
How to resolve InvalidVirtualFileAccessException?

### ISSUE THREAD

**Issue by kanwal123** [uber/okbuck#467]
Hello everyone, I am facing this problem and don't know what is it about. My event log is displaying this issue and my app is not running in the device while I am trying to run it. Please help me to resolve this issue. Thank you.
**Issue:**
InvalidVirtualFileAccessException: Accessing invalid virtual file: file://C:/Users/sanjay/AndroidStudioProjects/Calculator-Test/build/android-profile; original:261254; found:-

![This is my gradle code: ](https://user-images.githubusercontent.com/29795946/27761876-470c9672-5e7f-11e7-9c2e-3aee1d630065.PNG)

**Comment by kageiit** [comment]
This is because okbuck creates symlinks and they are not supported on windows. We have no plans for windows support right now. Ill add an item for this separately

**Comment by kageiit** [comment]
See #472
