### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by kageiit** [uber/okbuck#472]
Make okbuck generate caches/buck files that work on windows

**Comment by jbduncan** [comment]
I don't know if this is related to the caches or buck files being Windows-unfriendly, but when I try running `./buckw` from a Cygwin terminal on Windows 7, it causes the following error message to appear:

```text
chmod: cannot access '': No such file or directory
./buckw: line 247: exec: : not found
```

**Comment by jbduncan** [comment]
Heck, it may have something to do with the Gradle setup of the project I'm testing OkBuck against.

I could provide a reproducible example if desired. :)

**Comment by jbduncan** [comment]
Oh, and it might have something to do with how Buck only supports Windows 10, according to https://buckbuild.com/setup/getting_started.html. :/

**Comment by kageiit** [comment]
This is unlikely to be supported
