### ISSUE TITLE
:setupOkbuck execution time regression (sometimes it takes 1m+)

### ISSUE THREAD

**Issue by artem-zinnatullin** [uber/okbuck#473]
We're facing non-deterministic regression in `./buckw project` execution time after updating OkBuck from 0.20.4 to 0.22.4.

Expected behavior:

`setupOkbuck` should take 10-30 seconds.

Actual behavior:

`setupOkbuck` takes 50-120 seconds sometimes.

---

Environment: 

- OS: macOS Sierra 10.12.5
- JDK/JVM: Oracle JDK 1.8.0_131
- Gradle: 4.0.1 (happens with 3.5 as well)
- Android Gradle Plugin: 2.3.3
- OkBuck: 0.22.4 (we think regression started somewhere around 0.20.7)

---

Details of our investigation so far:

- We don't see this problem with OkBuck 0.20.4 and Gradle 4.0.1
- First time we've noticed it was May 25 when we've tried to upgrade OkBuck to 0.20.9
- Issue is definitely non-deterministic, but once you catch it, it'll be much more reproducible until you remove Gradle and Buck build folders
- It might be related to changes from #437 ("Use stream instead of parallelStream") which may create bottleneck in some cases.

Example of build log output:

```console
:setupOkbuck (Thread[Task worker,5,main]) started.
:setupOkbuck
Putting task artifact state for task ':setupOkbuck' into context took 0.0 secs.
Executing task ':setupOkbuck' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:setupOkbuck (Thread[Task worker,5,main]) completed. Took 1 mins 45.773 secs.
```

@bencodes tried to investigate this back in May 25 and pointed that this was in his build log during long `setupOkbuck` task execution:

```console
> Task :setupOkbuck
Putting task artifact state for task ':setupOkbuck' into context took 0.0 secs.
Executing task ':setupOkbuck' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Creating new cache for metadata-2.23/module-artifacts, path /Users/user/.gradle/caches/modules-2/metadata-2.23/module-artifacts.bin, access org.gradle.cache.internal.DefaultCacheAccess@58c0d216
// Nothing in output for long time.
```

We'll try to add more info, but since it's non-deterministic it's really hard to debug and profile.

**Comment by kageiit** [comment]
Can you try to attach a profiler to the gradle daemon when okbuck runs?

We have close to 1000 gradle modules and okbuck is usually ~30-40 seconds. It could be something in your setup as well

How many modules do you have?

**Comment by artem-zinnatullin** [comment]
Looks like we've found pretty stable way to reproduce it — switch to pretty diverse branch, run `./buckw project`, switch back to your branch and run `./buckw project` again — observe long `:setupOkbuck` execution time.

Our developers are hitting this issue when they switch between their feature branches and rebase with origin.

We have about 200 modules.

---

Profiling:

According to profiler, Gradle spends most of the time in file tree walking, and there is a method from OkBuck presented in such call stacks `com.uber.okbuck.core.dependency.DependencyCache.fetchSourcesFor()` which can take 35 and more seconds.

<img width="1434" alt="screen shot 2017-07-18 at 8 54 41 pm" src="https://user-images.githubusercontent.com/967132/28350330-2adfc510-6bfd-11e7-992e-b686ebd5a9b5.png">

What's also interesting is that during profiling I was seeing this message for long times as @Bencodes pointed before:

```console
:setupOkbuck
Putting task artifact state for task ':setupOkbuck' into context took 0.0 secs.
Executing task ':setupOkbuck' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.

// This one.
Creating new cache for metadata-2.23/module-artifacts, path /Users/user/.gradle/caches/modules-2/metadata-2.23/module-artifacts.bin, access org.gradle.cache.internal.DefaultCacheAccess@10e8c0f3
```

I suspect that regression was introduced in PR #423 where behavior of `DependencyCache.fetchSourcesFor()` was changed.

**Comment by artem-zinnatullin** [comment]
Another trace, `DependencyCache.fetchSourcesFor()` took 68 seconds.

<img width="1480" alt="screen shot 2017-07-18 at 9 30 34 pm" src="https://user-images.githubusercontent.com/967132/28350819-623ac23c-6c00-11e7-8fed-5dd6f2aeeb48.png">

Everything I did is what I explained above: switch to another branch, run `./buckw project`, switch back, run `./buckw project`, observe long execution of `:setupOkbuck`.

**Comment by kageiit** [comment]
This seems very suspicious. I think bulk of the time is being spent here walking the sources tree parent, which is what the fix was for.

Can you try two things
- `rm -rf ~/.gradle/caches`
- set `okbuck.intellij.sources = false`

To see if either of those do not show the behavior you are noticing. This usually tends to happen with snapshot artifacts etc. which may not have source artifacts

**Comment by artem-zinnatullin** [comment]
* `rm -rf ~/.gradle/cache` did not help, first build after that took 4 minutes (because it downloads deps again), second took about 70 seconds which is also slow.
* `okbuck.intellij.sources = false` reduced `buckw project` execution time to 6 seconds (Gradle part), but we need to generate IntelliJ files…

I don't see snapshot dependencies in our project, but there might be dependencies without source artifacts. Also, afaik OkBuck now prohibits snapshot deps anyway #447.

**Comment by kageiit** [comment]
okbuck just warns you with #447 . It still does not fail unless you enable that behavior.

btw if you go to the deepest in the stack can you see what part of okbuck is invoking that filetree walker logic? Also, are you sure you do not have filetree logic in your buildscript?

After the fix in #423 , we have not seen any regressions in okbuck perf due to the file walk atleast

**Comment by artem-zinnatullin** [comment]
Call stack contains following OkBuck method calls:

```java
69.5% - 68,957 ms com.uber.okbuck.core.dependency.DependencyCache.fetchSourcesFor
 69.5% - 68,957 ms com.uber.okbuck.core.dependency.DependencyCache$_build_closure4.doCall
  69.5% - 68,957 ms com.uber.okbuck.core.dependency.DependencyCache.build
   69.5% - 68,957 ms com.uber.okbuck.core.dependency.DependencyCache.<init>
    69.5% - 68,957 ms com.uber.okbuck.OkBuckGradlePlugin$_apply_closure2$_closure9.doCall
```

So it seems to be invoked by `apply plugin: 'com.uber.okbuck'` in the root `build.gradle` of our project, I don't see other file tree walking logic in our Gradle scripts.

**Comment by kageiit** [comment]
`okbuck.intellij.sources = false` does not stop generated intellij files. It will just not attach source jars to third party libraries so it can be a viable fix in the short term.

If you can add a breakpoint/print to that point in okbuck to see which folder it is trying to crawl, we will get a clue what is going on

**Comment by artem-zinnatullin** [comment]
Posted PR with fix and detailed explanations #479.

In our case issue was caused by 4 `.jar` stored in the project directory and used as dependencies (I'll try to fix this in near future by pushing them to own Artifactory). 

Each jar caused `fileTree` lookup through whole project directory which contains lots of subfolders and small files (`.git`, `.okbuck`, `build`, etc).

**Comment by artem-zinnatullin** [comment]
@kageiit you probably didn't see the issue in Uber projects because either you pull all dependencies from maven repos or you have some `.jar`s in the project but deep enough so `.jar/../../` is not a directory with lots of files as it were in our case 😸

**Comment by kageiit** [comment]
Ya we do not checkin jar files into our repos. We host them all on artifactory :)

**Comment by artem-zinnatullin** [comment]
What about `buck-android-support.jar`? 

I'm about to file an issue against https://github.com/facebook/buck/ to ask them to publish `buck-android-support.jar` to some public maven repo, but would be great to hear your solution first!

**Comment by kageiit** [comment]
We just uploaded it manually under some `com.facebook` group to artifactory

**Comment by artem-zinnatullin** [comment]
Yeah, that's what I would like to avoid, filed https://github.com/facebook/buck/issues/1431
