### ISSUE TITLE
error deal with debugCompile and releaseCompile by "gradle okbuck -Dobuck.wrapper=true"?

### ISSUE THREAD

**Issue by guhan121** [uber/okbuck#474]
first i rm -rf  ~/.gradle/caches/modules-2
when i run "./gradlew :app:dependencies ",  i got

debugCompile - Classpath for compiling the debug sources.
+--- com.antfortune.freeline:runtime:0.8.5
+--- com.atom.mobile.plugin:love:6.5.4-SNAPSHOT
\--- com.atom.mobile.plugin:share:6.5.3

releaseCompile - Classpath for compiling the release sources.
+--- com.antfortune.freeline:runtime-no-op:0.8.5
+--- com.atom.mobile.plugin:love:6.5.4-SNAPSHOT
\--- com.atom.mobile.plugin:share:6.5.3

I find gradle download  com.atom.mobile.plugin:love debug and release aar files.

so i run "gradle okbuck -Dobuck.wrapper=true"
i got the “BUCK” file in app dir;
but
android_resource(res_debug)/android_library(src_debug)/android_manifest(manifest_debug) deps
like
		'//.okbuck/cache:com.atom.mobile.plugin.love-6.5.4_dev-SNAPSHOT-release.aar',
		'//.okbuck/cache:com.atom.mobile.plugin.share-6.5.3_dev-SNAPSHOT-release.aar',

they are same  in debug and release.

**Comment by kageiit** [comment]
Can you post a snippet of your gradle configuration? Its hard to understand what is going on without it

**Comment by guhan121** [comment]
in app.gradle
.....
android {
.....
}
dependencies{
...
}
//append Plugin to app
builtInPlugin("love", "${loveversion}")
builtInPlugin("share","${shareversion}")


void builtInPlugin(String name, String version) {
    dependencies {
        releaseCompile "com.atom.mobile.plugin:${name}:${version}:release@aar"
        debugCompile "com.atom.mobile.plugin:${name}:${version}:debug@aar"
    }
    tasks.whenTaskAdded { task ->
        task.doLast  {
            if (task.name == 'prepareDebugDependencies' ) {
                copyPluginRtxt(name, version, "debug")
                addPluginToPluginsConfigJson(name, version, "debug")
            } else if (task.name == 'prepareReleaseDependencies') {
                copyPluginRtxt(name, version, "release")
                addPluginToPluginsConfigJson(name, version, "release")
            }
        }
    }
}
......

**Comment by guhan121** [comment]
nothing!
