### ISSUE TITLE
how to force use custom progurad tool

### ISSUE THREAD

**Issue by guhan121** [uber/okbuck#477]
in root build.gradle
buildscript {
    repositories {
//        mavenLocal()
        maven { url 'http://repo.atom.com:8181/nexus/content/groups/public' }
        maven { url 'plugins'}
    }
    dependencies {
        classpath 'net.researchgate:gradle-release:2.0.2'
        classpath 'com.android.tools.build:gradle:2.2.3'
        .....
        classpath 'com.antfortune.freeline:gradle:0.8.5'

    }
     configurations.all {
        resolutionStrategy {
            force "net.sf.proguard:proguard-gradle:${atomproguard_version}"
        }
    }
}
in gradle.properties
atomproguard_version = 5.3.2.atom.19

This Is The Way to use our modified proguard tool
but 
when i "gradle okbuck -Dokbuck.wrapper=true"
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':okbuck'.
> Could not resolve all artifacts for configuration ':proguardDepCache'.
   > Could not find net.sf.proguard:proguard-base:.
     Searched in the following locations:
         http://repo.atom.com:8181/nexus/content/groups/public/net/sf/proguard/proguard-base//proguard-base-.pom
         http://repo.atom.com:8181/nexus/content/groups/public/net/sf/proguard/proguard-base//proguard-base-.jar
         file:/home/user/develop/libs/proguard-base-.jar
         file:/home/user/develop/libs/proguard-base.jar
         file:/home/user/develop/3rd/libs/proguard-base-.jar
         file:/home/user/develop/3rd/libs/proguard-base.jar
         file:/home/user/android-sdk-linux/extras/android/m2repository/net/sf/proguard/proguard-base//proguard-base-.pom
         file:/home/user/android-sdk-linux/extras/android/m2repository/net/sf/proguard/proguard-base//proguard-base-.jar
         file:/home/user/android-sdk-linux/extras/google/m2repository/net/sf/proguard/proguard-base//proguard-base-.pom
         file:/home/user/android-sdk-linux/extras/google/m2repository/net/sf/proguard/proguard-base//proguard-base-.jar
         file:/home/user/android-sdk-linux/extras/m2repository/net/sf/proguard/proguard-base//proguard-base-.pom
         file:/home/user/android-sdk-linux/extras/m2repository/net/sf/proguard/proguard-base//proguard-base-.jar
         file:/home/user/develop/client/libs/proguard-base-.jar
         file:/home/user/develop/client/libs/proguard-base.jar
         file:/home/user/develop/yymobile_core/libs/proguard-base-.jar
         file:/home/user/develop/yymobile_core/libs/proguard-base.jar
         file:/home/user/develop/3rd/download_center/libs/proguard-base-.jar
         file:/home/user/develop/3rd/download_center/libs/proguard-base.jar
     Required by:
         project :

also i modify 

buildscript {
    repositories {
//        mavenLocal()
        maven { url 'http://repo.atom.com:8181/nexus/content/groups/public' }
        maven { url 'plugins'}
    }
    dependencies {
        classpath 'net.researchgate:gradle-release:2.0.2'
        classpath 'com.android.tools.build:gradle:2.2.3'
        .....
        classpath 'com.antfortune.freeline:gradle:0.8.5'
        classpath "net.sf.proguard:proguard-gradle:${atomproguard_version}"
    }
}
run  "gradle okbuck -Dokbuck.wrapper=true" got "BUILD SUCCESSFUL"

but in .buckconfig.local 
.....
[tools]
	proguard = .okbuck/cache/proguard/proguard-base-5.3.2.jar

user@Hi-Fi-B85W:~develop$ ls .okbuck/cache/proguard/
proguard-base-5.3.2.jar

it looking okbuck conn't  understand 

configurations.all {
        resolutionStrategy {
            force "net.sf.proguard:proguard-gradle:${atomproguard_version}"
        }
if there is a SymbolicLink for "net.sf.proguard:proguard-gradle${atomproguard_version}" in dir($rootDir/ .okbuck/cache/)
i can modify .buckconfig.local file after okbuck tasks .
but it means i need look for jar in mavenlocal repo.
how can i fix it?

**Comment by kageiit** [comment]
okbuck will only support the standard proguard that ships with the android gradle plugin by default.

But in your case, you can do (in your root project)
```
tasks.getByName('okbuck').doLast {
   // Edit .buckconfig.local to replace the proguard jar okbuck generates with the location of your custom proguard jar
}
```

This will let you customize the proguard jar that buck runs during the build.

**Comment by guhan121** [comment]
yes ,i fix it by this way,thsnks!
