### ISSUE TITLE
proguard -applymapping 

### ISSUE THREAD

**Issue by guhan121** [uber/okbuck#478]
in rootDir have a mapping_base.txt
and /rootDir/app/proguard.cfg
we write -applymapping mapping_base.txt

after 
"gradle okbuck -Dokbuck.wrapper=true "
in 
.okbuck/cache/gen/app/release/proguard.pro
it still is
 -applymapping mapping_base.txt

after "buck build appRelease"

java.io.FileNotFoundException: /home/user/develop/buck-out/gen/.okbuck/gen/app/release/mapping_base.txt 

I think okbuck must modify this!

I modify it
-applymapping /home/user/develop/mapping_base.txt
for a test ,it is ok
but it seem not a universal way to fix it.

**Comment by kageiit** [comment]
You can use the `proguardFiles` dsl in the android gradle plugin instead of apply mapping as okbuck has no way to figure out auxilliary files from the build mode.

Just add your base mapping to the existing proguardFiles config instead
