### ISSUE TITLE
No value has been specified for property 'mainClassName'.

### ISSUE THREAD

**Issue by guhan121** [uber/okbuck#480]
git clone https://github.com/uber/okbuck.git

qiantao@dw-Hi-Fi-B85W:~/github/okbuck$ git diff

diff --git a/buildSrc/build.gradle b/buildSrc/build.gradle
index 05c8774..7c7eaf6 100644
--- a/buildSrc/build.gradle
+++ b/buildSrc/build.gradle
@@ -1,5 +1,6 @@
 plugins {
     id "groovy"
+    id "maven"
     id "maven-publish"
     id "com.jfrog.bintray" version "1.7"
 }
@@ -9,6 +10,7 @@ apply from: "../dependencies.gradle"
 repositories {
     jcenter()
     google()
+    mavenCentral()
 }
 
 tasks.withType(GroovyCompile) {
@@ -47,7 +49,7 @@ task sourcesJar(type: Jar) {
     classifier = 'sources'
 }
 
-def publishVersion = '0.23.2'
+def publishVersion = '0.23.2.1'
 group = 'com.uber'
 version = publishVersion
 def siteUrl = 'https://github.com/uber/okbuck'
@@ -66,6 +68,12 @@ publishing {
     }
 }
 
+uploadArchives { //发布插件到本地lib
+    repositories.mavenDeployer {
+        repository(url: uri('/home/qiantao/repo'))
+    }
+}
+
 bintray {
     user = project.properties.get("bintray.user")
     key = project.properties.get("bintray.apikey")
diff --git a/buildSrc/src/main/groovy/com/uber/okbuck/composer/android/AndroidTestRuleComposer.groovy b/buildSrc/src/main/groovy/com/uber/okbuck/composer/android/AndroidTestRuleComposer.groovy
index 642e214..96f1b5c 100644
--- a/buildSrc/src/main/groovy/com/uber/okbuck/composer/android/AndroidTestRuleComposer.groovy
+++ b/buildSrc/src/main/groovy/com/uber/okbuck/composer/android/AndroidTestRuleComposer.groovy
@@ -18,6 +18,10 @@ final class AndroidTestRuleComposer extends AndroidBuckRuleComposer {
             final List<String> aidlRuleNames,
             String appClass) {
 
+        println("AndroidTestRule compose")
+        for (String s in deps) {
+            println(s)
+        }
         List<String> testDeps = new ArrayList<>(deps)
         testDeps.add(":${src(target)}")
         testDeps.addAll(external(target.test.externalDeps))

qiantao@dw-Hi-Fi-B85W:~/github/okbuck$ ./gradlew uploadArchives

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':libraries:customLintLibrary:startScripts'.
> No value has been specified for property 'mainClassName'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by kageiit** [comment]
Can you specify what you are trying to do?

If you just want to publish a local okbuck to try out your changes, you can run

```
./gradlew :plugin:publishToMavenLocal
```

instead

**Comment by kageiit** [comment]
Closing as I think I have addressed the intent of the ticket. Please comment with more details if you need more info
