### ISSUE TITLE
buckw ignores git errors during Buck update

### ISSUE THREAD

**Issue by artem-zinnatullin** [uber/okbuck#486]
If you set wrong git commit/tag/reference in `.buckversion` and try to run `buckw project`, `buckw` will think that Buck was successfully updated while in fact there were errors:

```console
./buckw project
BUCK VERSION IS AT 9db765a957d8d4a3dff6de914ef9535582a668eb , BUT IT SHOULD BE wrong-commit. UPDATING BUCK 
Fetching origin
Fetching custom
error: pathspec 'wrong-commit' did not match any file(s) known to git.
Buck does not appear to have been built -- building Buck!

BUCK BUILT SUCCESFULLY
```

And in general it's quite dangerous to run such important script without `set -e`, would be great to refactor it so it'll work with `set -e`.

**Comment by kageiit** [comment]
Fixed in d5758a2217fb5d5e369f0b80a2354c8a814e2f0c

Moving it to `set -e` is a completely different effort which would require a significant refactor. It could be tracked separately
