### ISSUE TITLE
Duplicated retrolambda symlinks in okbuck cache

### ISSUE THREAD

**Issue by marcinkwiatkowski** [uber/okbuck#497]
Hey, just noticed that after I believe 0.24.6 update (or one of the earlier ones) the symlink to retrolamba jar gets duplicated. Don't think it actually affects anything. 

![screen shot 2017-08-04 at 2 32 53 pm](https://user-images.githubusercontent.com/737294/28987878-1def7a3a-7922-11e7-8713-f14c23fcce5c.png)

This is also reproducible in okbuck project.

**Comment by kageiit** [comment]
Good find. I will check whats going on, but since its just an extra harmless symlink, it should not be a problem for now.
