### ISSUE TITLE
Unable to pass custom AST library to lint .

### ISSUE THREAD

**Issue by artem-zinnatullin** [uber/okbuck#501]
We're using Retrolambda. 

Default AST library that Lint uses doesn't work with Retrolambda properly, so we need to apply `me.tatarka.retrolambda.projectlombok:lombok.ast:0.2.3.a2` from https://github.com/evant/android-retrolambda-lombok.

We've tried following config:

`module/build.gradle`:

```groovy
// Exclude standard lombok ast.
configurations.buckLint.exclude group: 'com.android.tools.external.lombok'

dependencies {
    // Include patched version of ast https://github.com/evant/android-retrolambda-lombok                
    buckLint 'me.tatarka.retrolambda.projectlombok:lombok.ast:0.2.3.a2'
}
```

But Lint still fails to parse lambda and method reference exceptions and `.okbuck/cache/lint` still has default ast library.

Environment:

 - OkBuck 0.25.2
 - Android Gradle Plugin 2.3.3
 - Gradle 4.1
 - Buck https://github.com/facebook/buck/commit/d54b5d3397044b054d7dd72b90ecd2e96a3e5b0e 

---

If we manually symlink `.okbuck/cache/lint/lombok-ast-0.2.3.jar` to patched ast version — Lint is able to process lambdas and method references.

**Comment by kageiit** [comment]
Okbuck switched over to d8 by default for desugaring lambdas so this issue seems obsolete
