### ISSUE TITLE
Don't set resource path in generated BUCK file when resources folder doesn't exist

### ISSUE THREAD

**Issue by nguyentruongtho** [uber/okbuck#504]
From a gradle file likes following

```
apply plugin: "groovy"

dependencies {
    compile gradleApi()
    compile localGroovy()
}
```

okbuck will generate:

```
groovy_library(
...
	resources = glob([
		'src/main/resources/**',
	]),
	resources_root = 'src/main/resources',
	unbundled_resources_root = 'src/main/resources',
...
```
even when `src/main/resources` doesn't exist.

okbuck doesn't have that issue with `java_library` or `kotlin_library`

**Comment by kageiit** [comment]
This has been fixed in recent okbuck. The behavior in the description does not occur anymore.
