### ISSUE TITLE
 Resolving configuration 'debugCompile' directly is not allowed

### ISSUE THREAD

**Issue by ltyhome** [uber/okbuck#567]
localhost:TNApp ltyhome$ ./buckw targets
NO PREVIOUS SUCCESSFUL OKBUCK RUN
RUNNING OKBUCK...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':MPChartLib:okbuck'.
> Resolving configuration 'debugCompile' directly is not allowed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 2 executed

 OKBUCK FAILED

**Comment by kageiit** [comment]
Seems like you are usign android gradle plugin version 3+ which is not yet supported by okbuck

**Comment by kageiit** [comment]
Dup of #502
