### ISSUE TITLE
./buckw targets failing

### ISSUE THREAD

**Issue by zorroblue** [uber/okbuck#571]
I am able to do the steps till `./gradlew :buckWrapper` successfully.
However, on trying to `./buckw targets`, I get the following error:

`bash: ./buckw: /usr/bin/env: bad interpreter: Text file busy`

When I googled this, I got to know that this happens if a rogue process opens the file for writing. When I checked the processes accessing the file using `lsof | grep "buckw"` and further using `ps`, I found it was just the java executable accessing.

How can I resolve this issue?

I am using Android Studio 3.0, Android Gradle plugin 3.0.1 and my gradle version is 4.1

**Comment by kageiit** [comment]
okbuck does not support AGP 3.0.1 . See https://github.com/uber/okbuck/pull/568 and use `0.33.0-alpha01` till we are able to merge the PR

**Comment by kageiit** [comment]
Dup of #502
