### ISSUE TITLE
Databinding, Windows

### ISSUE THREAD

**Issue by naixx** [uber/okbuck#583]
Hi. I have two questions.

Is databinding supported right now? Previously I saw that databindign wasn't supported, it was mentioned in issues. But right now I don't see any mentions that it is unsupported, so can I assume that it should work? Because right now buck complains about `Invalid reference`

Is windows supported? I'm getting error `WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\work\\...` And couldn't find any references to fix or mention. I assume that the problem is with separators.

Not sure if it is my build or it is "by design" as there no doc references. Version 0.33 alpha

**Comment by kageiit** [comment]
Databinding is not supported yet

Windows support is - #472

**Comment by kageiit** [comment]
Databinding support is #614

Closing this
