### ISSUE TITLE
./buckw build <target> failing

### ISSUE THREAD

**Issue by mafunes** [uber/okbuck#584]
I have the same issue as https://github.com/uber/okbuck/issues/580

The command `./gradlew :buckWrapper` work fine, however, on trying to `./buckw build <target>`, I get the following error:

bash: ./buckw: /usr/bin/env: bad interpreter: Text file busy

I checked the processes accessing the file using lsof | grep "buckw" and further using ps, I found it was just the java executable accessing.

I am using:
Android Studio 3.0, 
Android Gradle plugin 2.2.3
Gradle version is 3.5.1
OS Debian 9

**Comment by kageiit** [comment]
Can you please try with the latest okbuck version?

**Comment by kageiit** [comment]
It seems like some process is holding onto the file in write mode according to https://stackoverflow.com/questions/1384398/usr-bin-perl-bad-interpreter-text-file-busy

Can you see if any of the posted workarounds there help?

**Comment by leandroBorgesFerreira** [comment]
Thanks @kageiit. It works just fine. 

To solve the problem, I did this:

run: `lsof | grep buckw`

You will get something like this: `30998	/opt/jdk1.8.0_141/bin/java	/var/go/nu/some-path/buckw`

Take the number of the process trying to access the buckw and kill it. Like this:
`kill -9 30998`

**Comment by kageiit** [comment]
Closing as it seems to be a system issue with a workaround and not an okbuck specific issue.
