### ISSUE TITLE
Okbuck doesn't prioritize build flavor strings over main strings

### ISSUE THREAD

**Issue by gpeal** [uber/okbuck#588]
We have some debug product flavors that only compile part of our app. It's useful to differentiate these different apps. When using Gradle, we can either use string overrides in `src/flavor` or us a plugin like [easylauncher](https://github.com/akaita/easylauncher-gradle-plugin). However, neither of these work with buck/okbuck. I'm not sure whether the issue lies in buck or okbuck.

**Comment by kageiit** [comment]
See https://github.com/uber/okbuck/issues/393#issuecomment-279095348

Closing as dup
