### ISSUE TITLE
Failure: "2 proguard files found. Only one can be used."

### ISSUE THREAD

**Issue by galex** [uber/okbuck#601]
Hello,

Following the issue #600 when a buildType is configured with `minifyEnabled = true`, the following error shows up:
```
galex$ ./buckw targets
NO PREVIOUS SUCCESSFUL OKBUCK RUN
RUNNING OKBUCK...


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:okbuck'.
> 2 proguard files found. Only one can be used.
```
This is how the flavor is configured:
```
buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```
If I comment the `proguard-rules.pro` file, I get the following error:
```
> Proguard file /Users/galex/houzz/BuckTestApp/build/intermediates/proguard-files/proguard-android.txt-3.1.0-rc02 does not exist
```
If I comment the `getDefaultProguardFile('proguard-android.txt')` part, then everything is OK.

Thank you in advance for your help!

**Comment by kageiit** [comment]
Please remove `getDefaultProguardFile('proguard-android.txt')` instead and just use `'proguard-rules.pro'`

**Comment by aaronhe42** [comment]
Was there any reason multiple proguard files aren't supported?

**Comment by runningcode** [comment]
don't think so, PRs welcome!
