### ISSUE TITLE
FirebaseApp initialization unsuccessful

### ISSUE THREAD

**Issue by ricoharisin** [uber/okbuck#603]
hi

somehow `FirebaseApp` cannot be init when using okbuck

    I/FirebaseInitProvider: FirebaseApp initialization unsuccessful

    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process     com.xxxx. Make sure to call FirebaseApp.initializeApp(Context) first.

also my apps have multiple module and firebase dependency is compiled by another module and application depend to that module

playservice lib: 11.0.4
android gradle plugin: 2.3.3
okbuck: 0.32.2

any comment or help will be very appreciate 

thanks before

**Comment by kageiit** [comment]
Can you make a small sample project showcasing this issue. Its hard to repro/diagnose otherwise

**Comment by eggman87** [comment]
@kageiit ran into same, will try to add to that sample project from the functional interface issue.

**Comment by eggman87** [comment]
@kageiit added to sample @ https://github.com/eggman87/buck_method_reference_issue

Exception happens when calling:
`FirebaseInstanceId.getInstance().getToken()` 
Full stack:
```
04-18 18:54:38.500  9422  9422 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.okbucktesting.OkBuckApplication: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.okbucktesting. Make sure to call FirebaseApp.initializeApp(Context) first.
04-18 18:54:38.500  9422  9422 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
04-18 18:54:38.500  9422  9422 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
04-18 18:54:38.500  9422  9422 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
04-18 18:54:38.500  9422  9422 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
04-18 18:54:38.500  9422  9422 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
04-18 18:54:38.500  9422  9422 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
04-18 18:54:38.500  9422  9422 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 18:54:38.500  9422  9422 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
04-18 18:54:38.500  9422  9422 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
04-18 18:54:38.500  9422  9422 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.okbucktesting. Make sure to call FirebaseApp.initializeApp(Context) first.
04-18 18:54:38.500  9422  9422 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.getInstance(Unknown Source:56)
04-18 18:54:38.500  9422  9422 E AndroidRuntime: 	at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source:0)
04-18 18:54:38.500  9422  9422 E AndroidRuntime: 	at com.okbucktesting.OkBuckApplication.onCreate(OkBuckApplication.java:16)
04-18 18:54:38.500  9422  9422 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
04-18 18:54:38.500  9422  9422 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
```
This works on regular gradle builds.

**Comment by kageiit** [comment]
This is likely due to missing `google-services.json` - https://developers.google.com/android/guides/google-services-plugin

Recommended workaorund is to not rely on the gradle plugin and just check in the json file directly. I dont see the json file in the test repo as its being gitignored

**Comment by eggman87** [comment]
Yea if you add just the JSON file, the same exception will occur. 

Looks like whatever the google services gradle plugin does is required. Without the google services plugin running, firebase is not usable.

**Comment by kageiit** [comment]
Right. The plugin does something quite simple actually. it copies values from the json file and puts them in resources

like
```
<string name="google_app_id">Your API ID</string>
<string name="google_api_key">Your API KEY</string>
```

You can easily do this by hand and check it in instead of the json file. That is how we handle firebase usage internally. You can ofcourse make the okbuck task depend on the GoogleServicesTask similar to how we handle it for sqldelight - https://github.com/uber/okbuck/blob/49ec6b17de253b1b5296c32d356868e6cdb316a8/build.gradle#L99 (this is the plugin hook basically), but it would involve more tinkering

**Comment by RaphaelKalker** [comment]
I believe you don't need to rely on the gradle plugin to initialize your Firebase instance. One could manually set up the firebase instance as described here:
https://firebase.googleblog.com/2017/03/take-control-of-your-firebase-init-on.html

**Comment by ricoharisin** [comment]
sorry just checked this issue again, and thanks @eggman87 to provide the sample!

right now i'm using workaround by manually init firebase instance and it works

so i will close this issue for now
