### ISSUE TITLE
OkBuck doesn't generate instrumentation test target

### ISSUE THREAD

**Issue by kafji** [uber/okbuck#609]
In order for OkBuck to generate instrumentation test targets I should just set `okbuck.test.espresso` to `true`. Is that true?

Because when I create a new Android project and setup OkBuck (version 0.34.1) as this:
```
okbuck {
  buildToolVersion = "26.0.3"
  target = "android-26"
  test {
    espresso = true
  }
  lint {
    disabled = true
  }
}
```
The instrumentation test targets are not generated.

**Comment by kafji** [comment]
Repro https://github.com/kafji/okbuck609

**Comment by runningcode** [comment]
Yeah, I had this issue as well. You need to add a `AndroidManifest.xml` in the `androidTest` srcs. This isn't well documented.

**Comment by kafji** [comment]
@runningcode thanks.

Solved the problem by adding AndroidManifest.xml as runningcode said with this as its content:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="{my_app_package_name}">

  <instrumentation
      android:name="android.support.test.runner.AndroidJUnitRunner"
      android:targetPackage="{my_app_package_name}"/>

</manifest>
```
