### ISSUE TITLE
BuildConfig fields in Annotation fails to parse

### ISSUE THREAD

**Issue by BharathMG** [uber/okbuck#636]
Hi,

Thanks for bringing full kapt3 support! I'm facing an issue where if I include BuildConfig fields in Annotations, okbuck fails to parse it correctly. Here is the code,

    
     @FormUrlEncoded
     @POST("${BuildConfig.SIGNUP_PATH}")
     fun signup(@Field("email") email: String, @Field("password") password: String): Observable<Response<String>> 

When running okbuck build, it fails with error,

``
Build failed: Command failed with exit code 1.
stderr: logging: using Kotlin home directory /Users/bharathmg/Documents/project/.okbuck/cache/kotlin_home/libexec
logging: configuring the compilation environment
error: /Users/bharathmg/Documents/project/buck-out/annotation/service/__src_debug_stubs__/LoginAuthServiceI.java:9: error: element value must be a constant expression
    @retrofit2.http.POST(value = null)
``

When I check generated class in `buck-out` directory, it replaced `${BuildConfig.SIGNUP_PATH}` with `null` value. But in kapt3 generated tmp directory, it correctly shows value for this buildconfig field.

And if I check generated BuildConfig.class in `buck-out/bin/dataSyncService/lib__bin_debug#buildconfig_datasyncservice__classes/BuildConfig.class` I can see correct values.

OkBuck version: 0.37.1 

Am I doing something wrong here?

**Comment by kageiit** [comment]
This is not an okbuck issue. Its a failure in buck build. Please file the issue on https://github.com/facebook/buck/issues
