### ISSUE TITLE
No build file at RNSound/BUCK when resolving target //RNSound:res_debug.

### ISSUE THREAD

**Issue by breakingsword** [uber/okbuck#642]
JackdeMacBook-Pro:android jack$ ./buckw targets
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'files'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'files'
No build file at RNSound/BUCK when resolving target //RNSound:res_debug.

**Comment by breakingsword** [comment]
the buck file is this
`android_resource(
    name = 'res_debug',
    package = 'com.zmxv.RNSound',
    resource_union = True,
    deps = [
        '//.okbuck/cache:com.android.support.appcompat-v7-23.0.1.aar',
        '//.okbuck/cache:com.android.support.support-v4-23.0.1.aar',
        '//.okbuck/cache:com.facebook.fbui.textlayoutbuilder.textlayoutbuilder-1.0.0.aar',
        '//.okbuck/cache:com.facebook.fresco.drawee-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.fbcore-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.fresco-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.imagepipeline-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.imagepipeline-base-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.imagepipeline-okhttp3-1.0.1.aar',
        '//.okbuck/cache:com.facebook.react.react-native-0.44.0.aar',
        '//.okbuck/cache:com.facebook.soloader.soloader-0.1.0.aar',
        '//.okbuck/cache:org.webkit.android-jsc-r174650.aar',
    ],
    visibility = [
        'PUBLIC',
    ],
)

android_build_config(
    name = 'build_config_debug',
    package = 'com.zmxv.RNSound',
    values = [
        'String APPLICATION_ID = "com.zmxv.RNSound"',
        'String BUILD_TYPE = "debug"',
        'String FLAVOR = ""',
        'int VERSION_CODE = 1',
        'String VERSION_NAME = "1.0"',
    ],
    visibility = [
        'PUBLIC',
    ],
)

lib_deps = []

android_library(
    name = 'src_debug',
    srcs = glob([
        'src/main/java/**/*.java',
    ]),
    source = '7',
    target = '7',
    provided_deps = [
        '//.okbuck/cache/d8:rt-stub.jar',
    ],
    manifest = '//.okbuck/gen/RNSound/debug:AndroidManifest.xml',

    deps = [
        '//.okbuck/cache:com.android.support.appcompat-v7-23.0.1.aar',
        '//.okbuck/cache:com.android.support.support-annotations-23.0.1.jar',
        '//.okbuck/cache:com.android.support.support-v4-23.0.1.aar',
        '//.okbuck/cache:com.facebook.fbui.textlayoutbuilder.staticlayout-proxy-1.0.jar',
        '//.okbuck/cache:com.facebook.fbui.textlayoutbuilder.textlayoutbuilder-1.0.0.aar',
        '//.okbuck/cache:com.facebook.fresco.drawee-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.fbcore-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.fresco-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.imagepipeline-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.imagepipeline-base-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.imagepipeline-okhttp3-1.0.1.aar',
        '//.okbuck/cache:com.facebook.react.react-native-0.44.0.aar',
        '//.okbuck/cache:com.facebook.soloader.soloader-0.1.0.aar',
        '//.okbuck/cache:com.google.code.findbugs.jsr305-3.0.0.jar',
        '//.okbuck/cache:com.parse.bolts.bolts-tasks-1.4.0.jar',
        '//.okbuck/cache:com.squareup.okhttp3.okhttp-3.4.1.jar',
        '//.okbuck/cache:com.squareup.okhttp3.okhttp-urlconnection-3.4.1.jar',
        '//.okbuck/cache:com.squareup.okhttp3.okhttp-ws-3.4.1.jar',
        '//.okbuck/cache:com.squareup.okio.okio-1.9.0.jar',
        '//.okbuck/cache:javax.inject.javax.inject-1.jar',
        '//.okbuck/cache:org.webkit.android-jsc-r174650.aar',
        ':build_config_debug',
        ':res_debug',
    ],
    visibility = [
        'PUBLIC',
    ],
)

android_resource(
    name = 'res_release',
    package = 'com.zmxv.RNSound',
    resource_union = True,
    deps = [
        '//.okbuck/cache:com.android.support.appcompat-v7-23.0.1.aar',
        '//.okbuck/cache:com.android.support.support-v4-23.0.1.aar',
        '//.okbuck/cache:com.facebook.fbui.textlayoutbuilder.textlayoutbuilder-1.0.0.aar',
        '//.okbuck/cache:com.facebook.fresco.drawee-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.fbcore-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.fresco-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.imagepipeline-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.imagepipeline-base-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.imagepipeline-okhttp3-1.0.1.aar',
        '//.okbuck/cache:com.facebook.react.react-native-0.44.0.aar',
        '//.okbuck/cache:com.facebook.soloader.soloader-0.1.0.aar',
        '//.okbuck/cache:org.webkit.android-jsc-r174650.aar',
    ],
    visibility = [
        'PUBLIC',
    ],
)

android_build_config(
    name = 'build_config_release',
    package = 'com.zmxv.RNSound',
    values = [
        'String APPLICATION_ID = "com.zmxv.RNSound"',
        'String BUILD_TYPE = "release"',
        'String FLAVOR = ""',
        'int VERSION_CODE = 1',
        'String VERSION_NAME = "1.0"',
    ],
    visibility = [
        'PUBLIC',
    ],
)

lib_deps = []

android_library(
    name = 'src_release',
    srcs = glob([
        'src/main/java/**/*.java',
    ]),
    source = '7',
    target = '7',
    provided_deps = [
        '//.okbuck/cache/d8:rt-stub.jar',
    ],
    manifest = '//.okbuck/gen/RNSound/release:AndroidManifest.xml',

    deps = [
        '//.okbuck/cache:com.android.support.appcompat-v7-23.0.1.aar',
        '//.okbuck/cache:com.android.support.support-annotations-23.0.1.jar',
        '//.okbuck/cache:com.android.support.support-v4-23.0.1.aar',
        '//.okbuck/cache:com.facebook.fbui.textlayoutbuilder.staticlayout-proxy-1.0.jar',
        '//.okbuck/cache:com.facebook.fbui.textlayoutbuilder.textlayoutbuilder-1.0.0.aar',
        '//.okbuck/cache:com.facebook.fresco.drawee-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.fbcore-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.fresco-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.imagepipeline-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.imagepipeline-base-1.0.1.aar',
        '//.okbuck/cache:com.facebook.fresco.imagepipeline-okhttp3-1.0.1.aar',
        '//.okbuck/cache:com.facebook.react.react-native-0.44.0.aar',
        '//.okbuck/cache:com.facebook.soloader.soloader-0.1.0.aar',
        '//.okbuck/cache:com.google.code.findbugs.jsr305-3.0.0.jar',
        '//.okbuck/cache:com.parse.bolts.bolts-tasks-1.4.0.jar',
        '//.okbuck/cache:com.squareup.okhttp3.okhttp-3.4.1.jar',
        '//.okbuck/cache:com.squareup.okhttp3.okhttp-urlconnection-3.4.1.jar',
        '//.okbuck/cache:com.squareup.okhttp3.okhttp-ws-3.4.1.jar',
        '//.okbuck/cache:com.squareup.okio.okio-1.9.0.jar',
        '//.okbuck/cache:javax.inject.javax.inject-1.jar',
        '//.okbuck/cache:org.webkit.android-jsc-r174650.aar',
        ':build_config_release',
        ':res_release',
    ],
    visibility = [
        'PUBLIC',
    ],
)

`

**Comment by kageiit** [comment]
Seems like an error in watchman

do a `watchman watch-del-all` and try again
