### ISSUE TITLE
Is data-binding supported for kotlin project?

### ISSUE THREAD

**Issue by atiwari-pretlist** [uber/okbuck#651]
I am trying to build android kotlin project with okbuck but facing issues related to data-binding.
Could you please confirm if data-binding is supported with okbuck? Thanks.

**Comment by runningcode** [comment]
Nope. Take a look at the features page on the wiki: https://github.com/uber/okbuck/wiki/Features

**Comment by atiwari-pretlist** [comment]
Ok thanks.
Is there any plan to support data-binding in near future?

**Comment by kageiit** [comment]
Dup of #614 . Please move conversation there
