### ISSUE TITLE
Error with ./buckw targets: libs must be located inside ...

### ISSUE THREAD

**Issue by tuanchauict** [uber/okbuck#672]
I have a quite complex structure project with module located inside module and share the same `libs` folder like this:
```gradle
// major's build.gradle
sourceSets {
    main {
        jniLibs.srcDirs = ['libs']
    }
}

// keep's build.gradle
sourceSets {
    main {
        jniLibs.srcDirs = ['../../libs']
    }
}
```

When I run `./buckw targets`, I got 

```
* What went wrong:
Execution failed for task ':line-keep:okbuck'.
> /Users/tuancv/workspace/android/LineChatClient/line-android/libs must be located inside /Users/tuancv/workspace/android/LineChatClient/line-android/ext/line-keep
```

Gradle: 4.7
OkBuck: 0.39.0

**Comment by kageiit** [comment]
`jniLibs.srcDirs = ['../../libs']` is not supported. You cannot have the same folder shared by two targets.

I would recommend you create a separate module for the libs and other modules depend on it instead
