### ISSUE TITLE
Not running okbuck for mudoles that contains -h in the name

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [uber/okbuck#676]
Hi folks!

I can see that, if I try to run many build at once using buckw, it doesn't run okbuck as is expected. 

If I run: 

```
./buckw build \
    //android/android-foundation/fondation:src_debug \
    //android/android-bonafont/bonafont:src_debug \
```

It goest just fine. But if I add a third library, it doesn't run okbuck and doesn't generate de BUCK files. 

Likes this:

```
./buckw build \
    //android/android-foundation/fondation:src_debug \
    //android/android-bonafont/bonafont:src_debug \
    //android/android-help/help:src_debug \
```

I end up with: 

```
BUILD FAILED: //android/android-foundation/fondation:src_debug references non-existent directory android/android-foundation/fondation
```

The error is expected, since okbuck didn't run

**Comment by kageiit** [comment]
Can you check if your watchman is working correctly? If you add a new gradle file and a new module, it should re-run okbuck

**Comment by leandroBorgesFerreira** [comment]
Uhm, I am deleting .okbuck folder before trying to run the build and I can see this behaviour even in our CI without watchman installed. I am trying to make it run for the first time.

**Comment by leandroBorgesFerreira** [comment]
I am debuging and so far I got: When you have more than modules do build it goes straight to the first if in `setupBuckRun()`

**Comment by leandroBorgesFerreira** [comment]
Found it. Just a sec.

**Comment by leandroBorgesFerreira** [comment]
This problem is not related at all with the number of modules being built. It is a small problem in the skip logic.

There's a problem in this part of buckw:

```
# Handle parameters and flags
handleParams ( ) {
   # Go directly to the kill command, help command, or --help option. Do not run okbuck.
   if [[ "kill" == $1 || "help" == $1 || $@ == *"--help"* || $@ == *"-h"* ]]; then
      SKIP_OKBUCK=true
   fi
}
```
Since our module has: `android-help` the `-h` check is passing. I believe the correct code should be:

```
# Handle parameters and flags
handleParams ( ) {
   # Go directly to the kill command, help command, or --help option. Do not run okbuck.
   if [[ "kill" == $1 || "help" == $1 || $@ == *"--help"* || $@ == *" -h "* ]]; then
      SKIP_OKBUCK=true
   fi
}
```

I mean: `$@ == *" -h "*`instead of $@ == *"-h"*

**Comment by kageiit** [comment]
@leandroBorgesFerreira Please modify your repo's buckw directly till we cut a new okbuck release. Thanks for fixing!
