### ISSUE TITLE
OkBuck generating same rules with difference in deps

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [uber/okbuck#683]
Removing the filter in the rules generation I can see that OkBuck is generating the same resource rules, but with a small difference in deps. 

Running OkBuck we got those rules:
```
#Rule 1
android_resource(
    name = 'res_debug_test',
    package = 'our.awsome.package.test',
    resource_union = True,
    deps = [
       [many deps here]
    ],
    visibility = [
        'PUBLIC',
    ],
)

#Rule 2
android_resource(
    name = 'res_debug_test',
    package = 'our.awsome.package.test',
    resource_union = True,
    deps = [
        [many deps here]
        ':res_debug', // This is one is not in the Rule 1!
    ],
    visibility = [
        'PUBLIC',
    ],
)
```

The problem of duplicated rules is addressed in PR 682. But the fact that the second rule is removed without a logic to confirm if it is the right one might be a problem.

**Comment by kageiit** [comment]
This has been fixed in #706
