### ISSUE TITLE
No resource found on android support library

### ISSUE THREAD

**Issue by aldochristiaan** [uber/okbuck#688]
Hello, I'm using okbuck v0.38 that compatible with gradle 4.4 well ..
But I got this error , when i try to build my app ..

```
buck-out/bin/.okbuck/cache/__unpack_com.android.support.appcompat-v7-26.0.2.aar#aar_unzip__/res/values-v26/values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

buck-out/bin/.okbuck/cache/__unpack_com.android.support.design-26.0.2.aar#aar_unzip__/res/values-v26/values-v26.xml:4: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
```

Can you guys help please ?

**Comment by kageiit** [comment]
This is a bug in buck. Please open a ticket there.

I would suggest updating your buck version to latest (https://github.com/facebook/buck/commit/7aa70a6ddc1d3bb7629801a92f5b4dbfc7d477dc) to see if its still a problem before doing so.

to upgrade buck, follow instructions in https://github.com/uber/okbuck/wiki/OkBuck-options-and-examples

```
okbuck {
    // Set a specific buck binary or alternate buck distribution.
    buckBinary = "com.github.facebook:buck:7aa70a6ddc1d3bb7629801a92f5b4dbfc7d477dc@pex"
}

}
