### ISSUE TITLE
Move metadata generation required for build from okBuck to buck

### ISSUE THREAD

**Issue by raviagarwal7** [uber/okbuck#691]
Currently there are a bunch of metadata generated by okBuck which adds to the okBuck run time as the project size increases. Idea is to move these into buck generated files so these metadata generation can move to build time which will be parallelized and cached. 

- [x] Generating merged android manifests file
- [x] Extracting lint jars from dependencies
- [x] Signing keys
- [x] Groovy, Kotlin Installation
- [x] Robolectric Runtime Dependencies
- [x] Downloading of maven artifacts

We are going to start with grouping dependencies name-spaced by group and name, generating explicit `prebuilt_jar` rules for each dependency. This will allow us to:
- Have all 3rd party dependencies in one place. 
- Remove usages of regex and glob to generate prebuilt rules at build parsing time
- Move to skylark which doesn't support above behaviour

eg:
```
╰─$ cat 3rdparty/android/arch/core/BUCK
android_prebuilt_aar(
    name = 'runtime',
    aar = 'runtime.aar',
    source_jar = 'runtime-sources.jar',
    visibility = ['PUBLIC'],
)

prebuilt_jar(
    name = 'common',
    binary_jar = 'common.jar',
    source_jar = 'common-sources.jar',
    maven_coords = 'android.arch.core:common:jar:1.1.0',
    visibility = ['PUBLIC'],
)
```

**Comment by raviagarwal7** [comment]
cc @kageiit

**Comment by kageiit** [comment]
cc @artem-zinnatullin @cwoodwar6 @seanabraham

**Comment by artem-zinnatullin** [comment]
Btw, if OkBuck will stop relying on symlinking for dependency resolution on Buck side, that can potentially unlock Gradle build cache for Okbuck

LGTM 👍

**Comment by thalescm** [comment]
We use aws s3 for private maven, and we currently use a gradle plugin for that. Do you know if that is possible with `maven_coords` parameter or `remote_file` rules?  (I didn't find any good documentation on it)

**Comment by kageiit** [comment]
It should be possible to still use `remote_file` for those
