### ISSUE TITLE
Usable with non-Android projects?

### ISSUE THREAD

**Issue by filipwski** [uber/okbuck#693]
Hi. Is it possible to use OkBuck with a non-Android gradle-based project?

**Comment by artem-zinnatullin** [comment]
Yes, it supports plain Java/Kotlin modules (I think Groovy and Scala are also supported but I haven't tried)

**Comment by kageiit** [comment]
It should be usable with non android projects. See https://github.com/uber/okbuck/wiki/Features for list of all supported languages
