### ISSUE TITLE
Support -Xfriend-paths for kotlin internal

### ISSUE THREAD

**Issue by hzsweers** [uber/okbuck#709]
It's present as of 1.2.70-EAPs, and enables access to `internal` classes from tests in the same project

CC @cwoodwar6

**Comment by cwoodwar6** [comment]
I believe that https://youtrack.jetbrains.com/issue/KT-21910 would need to be addressed first. cc @thalescm

**Comment by hzsweers** [comment]
It's possible as of 1.2.70 EAP 1, which we're now on RC1 :)

**Comment by cwoodwar6** [comment]
Ah got it. I didn't see a version on that ticket.

**Comment by thalescm** [comment]
This is beautiful, unit testing SDKs (which is normally where you can't remove internal things) with buck was kind of hard. had to trust only in integration tests. This will be very good

**Comment by hzsweers** [comment]
Bazel implementation: https://github.com/bazelbuild/rules_kotlin/pull/142

Note that the buck maintainers closed this as wontfix because they don't support kotlin: https://github.com/facebook/buck/issues/2029
