### ISSUE TITLE
Flavor Dimension Support

### ISSUE THREAD

**Issue by almozavr** [uber/okbuck#72]
Looks like flavor dimensions are not supported at the moment, `okbuck` command gives an error.
### Gradle setup

``` groovy
android {
  defaultConfig {
    ...
    flavorDimensions "type", "version"
  }
  productFlavors {
        dev {
            dimension "type"
            minSdkVersion 23
        }
        prod {
            dimension "type"
        }
        standart {
            dimension "version"
        }
        pro {
            dimension "version"
        }
  }
}
```
### Error

```
* What went wrong:
Execution failed for task ':okbuck'.
> AndroidSourceSet with name 'devDebug' not found.
```

[Gist for AndroidTDDBootStrap](https://gist.github.com/almozavr/a9ae06052846ce213d65b11472005983)

**Comment by kageiit** [comment]
Flavor dimensions dont crash the okbuck task anymore. But okbuck also does not generate any buck build rules for flavor dimensions yet. This will be added

**Comment by andreas-** [comment]
+1

**Comment by kageiit** [comment]
Would like to welcome PRs for this feature

**Comment by probepark** [comment]
+1

**Comment by YMChang** [comment]
+1

**Comment by kageiit** [comment]
This is supported once #568 merges as AGP 3.x explicitly requires dimensions for all flavors

**Comment by kageiit** [comment]
Please follow #502 for updates

Dup of #502
