### ISSUE TITLE
./buckw targets commands fails at BUILD FAILED: The rule //.okbuck/gen/app/release:app.keystore could not be found. 

### ISSUE THREAD

**Issue by shaliniprajeshwynk** [uber/okbuck#726]
~/AndroidStudioProjects/MyApplication $ ./buckw targets
CHANGES DETECTED IN:
app/build.gradle

RUNNING OKBUCK...

BUILD SUCCESSFUL in 1s
4 actionable tasks: 4 executed

PROCEEDING WITH BUCK

BUILD FAILED: The rule //.okbuck/gen/app/release:app.keystore could not be found.
Please check the spelling and whether it exists in /Users/b0207281/AndroidStudioProjects/MyApplication/.okbuck/gen/app/release/BUCK.

This error happened while trying to get dependency '//.okbuck/gen/app/release:app.keystore' of target '//app:bin_release'

Here is my root build.gradle 
    `   // Top-level build file where you can add configuration options common to all sub- 
       projects/modules.

    buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath 'com.uber:okbuck:0.40.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        }
      }

     allprojects {
        repositories {
             google()
             jcenter()
           }
       }

      task clean(type: Delete) {
          delete rootProject.buildDir
      }

     apply plugin: 'com.uber.okbuck'

      okbuck {
          lint {
               disabled = true
          }
     }`

**Comment by kageiit** [comment]
This should be fixed in the next release of okbuck

**Comment by kageiit** [comment]
Fixed in 0.41.0
