### ISSUE TITLE
Proguard file not found

### ISSUE THREAD

**Issue by mafunes** [uber/okbuck#740]
I get the following error when trying to run `./buckw build //app:bin_release`

Shows an error message

BUILD FAILED

> //app:src_debug:` parameter 'proguardConfig': no such file or directory 'app/proguard-rules.pro'

My `build.gradle` file has **proguard-android.pro** instead **proguard-rules.pro**

```
buildTypes {
        release {
            proguardFiles 'proguard-android.pro'
        }
}
```

**Comment by kageiit** [comment]
Does the file exist? Can you try to do `rm -rf .okbuck` and try again?

**Comment by mafunes** [comment]
The version of okbuck is 0.41.0

**Comment by kageiit** [comment]
This should not longer be an issue with the latest okbuck. Please re-open if it happens on latest
