### ISSUE TITLE
android_instrumentation_apk and android_instrumentation_test rules generated only for `debug` build type

### ISSUE THREAD

**Issue by alexfdz** [uber/okbuck#756]
The buck rules related to instrumentation tests are only generated for the `debug` build type.

### How to reproduce

```
@:~/okbuck$ ./buckw targets //app/... --type android_instrumentation_apk android_instrumentation_test
//app:instrumentation_demoDebug_apk
//app:instrumentation_demoDebug_test
//app:instrumentation_devDebug_apk
//app:instrumentation_devDebug_test
//app:instrumentation_prodDebug_apk
//app:instrumentation_prodDebug_test
```

Is there any way to choose what build types should be used to generate these rules?

**Comment by kageiit** [comment]
as long as there is an androidTest build type with a valid manifest, it is picked up by okbuck

https://github.com/uber/okbuck/blob/6db1af3e07bbc70144090757847afc067c502e46/buildSrc/src/main/java/com/uber/okbuck/core/model/android/AndroidTarget.java#L488

**Comment by alexfdz** [comment]
Thanks for your reply @kageiit.

Sorry I am missing something, in [okbuck/app/src](https://github.com/uber/okbuck/tree/master/app/src) there is only one `androidTest`, agnostic to any build type.

Why then the rule is only created for `debug`?

**Comment by kageiit** [comment]
The query for manifest is made on the Android Gradle plugin dsl. The plugin defaults to debug for the sec/androidTest manifest

**Comment by alexfdz** [comment]
That makes sense, thanks @kageiit!

**Comment by alexfdz** [comment]
@kageiit I found it, the tests only can run against one build type.

> By default, all tests run against the debug build type. You can change this to another build type by using the testBuildType property in your module-level build.gradle file. For example, if you want to run your tests against your "staging" build type, edit the file as shown in the following snippet.
> 
> ```
> android {
>     ...
>     testBuildType "staging"
> }
> ```
> 

https://developer.android.com/studio/build/gradle-tips#change-the-test-build-type
