### ISSUE TITLE
[Lint] Lint should read from new lintChecks configurations

### ISSUE THREAD

**Issue by ZacSweers** [uber/okbuck#790]
In Android projects, there is a `lintChecks` configuration for libraries that can be used to indicate lint checks that should be bundled with it

For non-android projects, lint projects can be applied via lint plugin (`com.android.lint` I think, will confirm) and denoting lints that should be applied via the same `lintChecks`

From a high level:
- Android project? `lintChecks` means bundle this lint in the AAR
- Non-android project? `lintChecks` means run lints from this artifact

**Comment by hzsweers** [comment]
One open question on this: can we move off of `buckLint` entirely? I need to check how android lint projects are supposed to declare lints that are in both local projects and should also run _on_ the consuming project (vs. just exporting them). It may be the case that the convention is to make these checks a `lintChecks` dependency of a shim intermediary project so it sits in its aar, but that seems kind of awkward. Also unsure if okbuck would pick up lints from aars in internal projects (vs currently just reading them from external projects)

**Comment by kageiit** [comment]
buck does not create aars for cross project consumption and neither does gradle currently so we cannot use the approach you described

**Comment by hzsweers** [comment]
Makes sense, can keep `buckLint` for now then. Can maybe consolidate names if lint does have a configuration for consuming local projects

**Comment by kageiit** [comment]
if there is one, we can consolidate
