### ISSUE TITLE
OkBuck doesn't generate instrumentation test target in 'com.android.library' module

### ISSUE THREAD

**Issue by kirillzh** [uber/okbuck#795]
This issue is very similar to #609 except that my instrumentation tests are located in `com.android.library` module, not `com.android.application`. Normally that works just fine with Gradle but OkBuck doesn't seem to generate the instrumentation test target for some reason. I tried setting manifest file just like in #609 and setting test application ID in `build.gradle` but that didn't solve the problem.

**Comment by kageiit** [comment]
This was added in https://github.com/uber/okbuck/pull/616 iirc by @thalescm 

@thalescm can you comment if something changed?

**Comment by kirillzh** [comment]
So we were able to upgrade to buck `b1cc9a6e691f1f177b7c64eb7f4983f05fcf014b` and okbuck `0.47.0` thanks to @Blisse, but I'm still not seeing instrumentation targets being generated. Also tried running instrumentation tests from `libraries/kotlinandroidlibrary` but it also doesn't seem to be generating instrumentation targets for this module.
```
//libraries/kotlinandroidlibrary:bin_debug_test
//libraries/kotlinandroidlibrary:build_config_debug_test
//libraries/kotlinandroidlibrary:keystore_debug_test
//libraries/kotlinandroidlibrary:keystore_debug_test_properties
//libraries/kotlinandroidlibrary:lint_custom
//libraries/kotlinandroidlibrary:lint_debug
//libraries/kotlinandroidlibrary:lint_debug_test
//libraries/kotlinandroidlibrary:lint_release
//libraries/kotlinandroidlibrary:manifest_bin_debug_test
//libraries/kotlinandroidlibrary:manifest_lib_custom
//libraries/kotlinandroidlibrary:manifest_lib_debug
//libraries/kotlinandroidlibrary:manifest_lib_debug_test
//libraries/kotlinandroidlibrary:manifest_lib_release
//libraries/kotlinandroidlibrary:res_custom
//libraries/kotlinandroidlibrary:res_debug
//libraries/kotlinandroidlibrary:res_debug_test
//libraries/kotlinandroidlibrary:res_release
//libraries/kotlinandroidlibrary:src_custom
//libraries/kotlinandroidlibrary:src_debug
//libraries/kotlinandroidlibrary:src_debug_test
//libraries/kotlinandroidlibrary:src_release
//libraries/kotlinandroidlibrary:test_custom
//libraries/kotlinandroidlibrary:test_debug
//libraries/kotlinandroidlibrary:test_release
```

**Comment by thalescm** [comment]
The `//libraries/kotlinandroidlibrary:bin_debug_test` rule should be your instrumentation apk.
it is a normal `android_binary` rule and not an `android_instrumentation_apk` because the latter requires an `android_binary` rule as counterpart.
You can see an example is this repository (`libraries/kotlinandroidlibrary`) with how to setup.

**Comment by thalescm** [comment]
And that means (I haven't tested this, but I'm almost positive) that you won't be able to run it with `./buckw test` and rather use adb instead.
If that work out for you, please close the issue :)

**Comment by thalescm** [comment]
@kirillzh I'm closing the issue for now. Feel free to reopen it if you think the problem in okbuck remains

**Comment by kirillzh** [comment]
@thalescm, is it possible with pure Buck to set up android library (not app) and allow to run instrumentation tests on it? If yes, considering that Gradle supports it, that's the problem in OkBuck. Otherwise it would be Buck problem. Here's example of such Gradle module: https://github.com/googlesamples/android-testing-templates/blob/master/AndroidTestingBlueprint/module-android-library/src/androidTest/java/com/example/android/testing/blueprint/androidlibrarymodule/AndroidLibraryModuleTest.java.

**Comment by kirillzh** [comment]
Look what I found, @thalescm  😛 
https://github.com/facebook/buck/issues/1692
So I assume it's a buck problem?

**Comment by thalescm** [comment]
Yes, it is a buck problem :D
There is a way to overcome this, as I mentioned, and it exists in the repository at `libraries/kotlinandroidlibrary`.
If you run `./buckw build //libraries/kotlinandroidlibrary:bin_debug_test` the end result is a valid instrumentation apk. And the rule itself was generated by okbuck by recognising you have a test suit for your library.
what you **cannot** do is to have `./buckw test //libraries/kotlinandroidlibrary:bin_debug_test` as buck itself doesn't recognise `android_binary` as a testable rule, so to run the tests you have to go with [adb shell](https://developer.android.com/studio/test/command-line#RunTestsDevice), or use a vendor, such as firebase, etc...
