### ISSUE TITLE
Error building (mvn artifact hash mismatch) after successful OkBuck setup

### ISSUE THREAD

**Issue by erawhctim** [uber/okbuck#797]
I setup okbuck properly (to my knowledge) and now I'm getting a build error:
`Unable to download mvn:com.google.j2objc:j2objc-annotations:jar:1.1 (hashes do not match. Expected 2994a7eb78f2710bd3d3bfb639b2c94e219cedac0d4d084d516e78c16dddecf6, saw 40ceb7157feb263949e0f503fe5f71689333a621021aa20ce0d0acee3badaa0f)`

What does that mean? 

build command: `./buckw build //app:bin_stagingDebug`

Looking at the dependency graph via `./gradlew dependencies`, it looks like the j2ObjC lib is required by Truth, which is setup as a test-only dependency (if that's helpful).

I'm completely new to Buck/okbuck, so let me know if there is more detail I can provide or if this makes more sense as an issue on the main Buck repo (or a StackOverflow question). Just looking to gain insight on what this error means to help me investigate.

**Comment by kageiit** [comment]
Which version of okbuck, gradle and android gradle plugin are you using?

**Comment by erawhctim** [comment]
okbuck: 0.46.2
gradle: 4.7
gradle android plugin: 3.2.1

If I manually edit the SHA in `.okbuck/ext/com/google/j2objc/BUCK` to the hash that buck expects, the build succeeds - I don't yet know if that's ok or problematic for us, but it seems to solve my problem, so at this point I'm just more curious as to why it happened/where the discrepancy came from.

**Comment by kageiit** [comment]
@raviagarwal7 has been looking at a similar issue in https://github.com/uber/okbuck/pull/796

This could be the same issue

**Comment by erawhctim** [comment]
Good to know, thanks! I'm on Kotlin v1.3.10 as well, could very well be the same thing.

**Comment by erawhctim** [comment]
@raviagarwal7 ok great - thanks so much!

**Comment by raviagarwal7** [comment]
Seems like this is probably a metadata caching issue b/w different gradle versions. We might want to wipe out the gradle cache completely in such scenario to make sure the gradle cache is consistent.

an example with `kotlin-allopen`

With existing gradle home
```
╰─$ find /Users/ravi/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-allopen/1.3.11                                                                                                                                      130 ↵
/Users/ravi/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-allopen/1.3.11
/Users/ravi/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-allopen/1.3.11/81b97e2b26c50502e3402fad769e1831d1d7032d
/Users/ravi/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-allopen/1.3.11/81b97e2b26c50502e3402fad769e1831d1d7032d/kotlin-allopen-1.3.11.jar
/Users/ravi/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-allopen/1.3.11/7adf0f8fcbd6615c1f04b14742758d914ca3cb24
/Users/ravi/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-allopen/1.3.11/7adf0f8fcbd6615c1f04b14742758d914ca3cb24/kotlin-allopen-1.3.11.jar
```

With a different gradle home
```
╰─$ GRADLE_USER_HOME=~/.test/ ./gradlew okbuck -Dokbuck.wrapper=true --stacktrace
╰─$ find  ~/.test/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-allopen/1.3.11/
/Users/ravi/.test/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-allopen/1.3.11/
/Users/ravi/.test/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-allopen/1.3.11//81b97e2b26c50502e3402fad769e1831d1d7032d
/Users/ravi/.test/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-allopen/1.3.11//81b97e2b26c50502e3402fad769e1831d1d7032d/kotlin-allopen-1.3.11.jar
/Users/ravi/.test/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-allopen/1.3.11//647b79b8eaf0391edfbd8bd61c852915381d71a5
/Users/ravi/.test/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-allopen/1.3.11//647b79b8eaf0391edfbd8bd61c852915381d71a5/kotlin-allopen-1.3.11.pom
```

**Comment by kageiit** [comment]
We should report this upstream to gradle potentially. wiping out cache is not a practical solution for all :)

**Comment by kageiit** [comment]
This should not longer be an issue with the latest okbuck. Please re-open if it happens on latest
