### ISSUE TITLE
Set default user.country to prevent it from mismatch in different laptops

### ISSUE THREAD

**Issue by raviagarwal7** [uber/okbuck#810]
Set DEFAULT_JVM_OPTIONS=`-Duser.country=US -Duser.language=en` in gradlew to make sure `user.country` doesn't differ b/w machines
```
vm_args = [
     '-Djava.awt.headless=true',
     '-Dfile.encoding=UTF-8',
     '-Duser.country=US',
     '-Duser.language=en',
     '-Duser.variant',
     '-ea',
 ],
```

**Comment by kageiit** [comment]
These are only in test vm arguments so they dont cause cache key issues. They can only cause noise if BUCK files are checked in
