### ISSUE TITLE
Fix broken -Xfriend-paths after kotlin 1.3.20 upgrade

### ISSUE THREAD

**Issue by kageiit** [uber/okbuck#817]
See https://github.com/uber/okbuck/pull/802#issuecomment-463326871

**Comment by thalescm** [comment]
Apparently it should working wither by passing the directories with the classes, or by passing the archive, as [tested here](https://github.com/JetBrains/kotlin/blob/v1.3.20/compiler/tests/org/jetbrains/kotlin/cli/FriendPathsTest.kt).

Looking at the stacktrace, when reverting [this](https://github.com/uber/okbuck/pull/802/files#diff-2c2c5cba1a8a3ec4aab0fa722e1d0ad8L3) (so we get the error), and running
`./buckw test //libraries/kotlinlibrary:test_main -v 10`
we can see that friend paths is set:
```
-Xfriend-paths=buck-out/gen/libraries/kotlinlibrary/lib__src_main__output/src_main.jar
```

Looking at the generated BUCK file (on `libraries/kotlinlibrary/BUCK`:
```
kotlin_test(
    name = 'test_main',
    <...>,
    extra_kotlinc_arguments = [
        <...>
        '-Xfriend-paths=buck-out/gen/libraries/kotlinlibrary/lib__src_main__output/src_main.jar',
    ],
    <...>,
)
```
It seems that kotlin compiler is not able to use relative paths for `-Xfriend-paths` option. Checked gradle output, it uses absolute path on this argument. And if I change the BUCK file to use the absolute path to that jar, tests will compile as well.

**Comment by thalescm** [comment]
https://youtrack.jetbrains.com/issue/KT-29933

**Comment by kageiit** [comment]
Good catch. Another option we have in buck is to expand the path ourselves in the buck kotlin rules
