### ISSUE TITLE
Okbuck fetches wrong androidx artifact id after forcedOkbuck play services library

### ISSUE THREAD

**Issue by mmdango** [uber/okbuck#822]
repro: https://github.com/mmdango/okbuckkotlin130repro/tree/michael--supportlibs

After enabling jetifier and androidx, then using `forcedOkbuck` on certain Play Services libraries, Okbuck fetches the incorrect androidx artifact ids.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:okbuck'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not find support-v4.aar (androidx.legacy:legacy-support-v4:1.0.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/legacy/legacy-support-v4/1.0.0/support-v4-1.0.0.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Notice it is fetching `support-v4.aar` instead of `legacy-support-v4.aar`

**Comment by kageiit** [comment]
This can happen since forcedOkbuck pulls in transitive dependencies and forces their versions as well. You can fix this behavior by changing how you force this dependency. You can mark the forcedOkbuck dependency as `transitive = false` or use
```
allprojects {
    repositories {
        google()
        jcenter()
    }
    project.configurations.all {
        resolutionStrategy {
            forcedModules = [
                "com.google.android.gms:play-services-wallet:15.0.0"
            ]
        }
    }
}
```

Both changes make your branch pass okbuck
