### ISSUE TITLE
Resource merging does not appear to work properly

### ISSUE THREAD

**Issue by alexjlockwood** [uber/okbuck#825]
I have a PR here that reproduces the issue: https://github.com/uber/okbuck/pull/826

Library `A` and `B` are both Android libraries, where `B` depends on `A`.

Library `A` defines a single string resource:

```
<resources>

     <string name="string_a">String A</string>

 </resources> 
```

Since `B` depends on `A`, that means that `A`'s resources should be merged with `B`, and `B`, which means that the following should compile:

```
package com.uber.okbuck.example.common;

import com.uber.okbuck.example.libraryb.R;

public class TestB {

    TestB() {
        int i = R.string.string_a;
    }

}
```

However, executing `./buckw build //libraries/libraryB:src_release` results in the following error:

```
Command failed with exit code 1.
stderr: /Users/alockwood/okbuck/libraries/libraryB/src/main/java/com/uber/okbuck/example/common/TestB.java:8: error: cannot find symbol
        int i = R.string.string_a;
                        ^
  symbol:   variable string_a
  location: class com.uber.okbuck.example.libraryb.R.string
Errors: 1. Warnings: 0.

    When running <javac_jar>.
    When building rule //libraries/libraryB:src_release.
```

The only way I've found to workaround the issue is to reference the resource by its fully qualified name (i.e. `com.uber.okbuck.example.librarya.R.string_a` instead of `com.uber.okbuck.example.libraryb.R.string_a`). However, this should not be necessary. (I'm also unsure if it is safe to workaround this way either... if no resource merging is happening, I assume it is be possible for runtime `ResourceNotFoundException`s to occur).

Note that this is only an issue with Buck. Building with gradle (`./gradlew :libraries:libraryB:assembleRelease`) works as expected.

I believe this PR was the cause of the bug: facebook/buck#2086

Some others have been seeing the bug as well: facebook/buck#2196

**Comment by kageiit** [comment]
This should be opened against buck upstream.
