### ISSUE TITLE
Testing Support

### ISSUE THREAD

**Issue by kageiit** [uber/okbuck#83]
- [x] Java Unit Tests
- [x] Android Robolectric Unit Tests
- [x] Android Espresso UI Tests
- [x] Cobertura Code Coverage Report

**Comment by andreas-** [comment]
+1

**Comment by kageiit** [comment]
Unit testing support for java targets is now available in v0.2.0

**Comment by kageiit** [comment]
Making Robolectric tests work with buck requires a custom test runner. Plan to add it as an artifact/example to this repo before releasing Robolectric test support fully

**Comment by kageiit** [comment]
Code coverage is supported out of the box with the `--with-coverage` option in buck

**Comment by germanb** [comment]
Hi @kageiit, I'm trying to execute the unit tests with buck but it's not working. I also tried to clone this repo and I found that the java_test rule is generated for the libraries/javalibrary but it doesn't for app which contains the ExampleUnitTest.java.

**Comment by kageiit** [comment]
Yes, the robolectric android test support is guarded by an experimental flag in the `experimental` extension.

A couple of changes had to merge back to buck (https://github.com/facebook/buck/commit/8bd6dd13d3e1d3319cc37e7a271f71ddd2b3939d) before we could roll this out to everyone (only happened very recently). It also requires the usage of a custom robolectric test runner which we will add to this repo as an example.

The example in this repo should be runnable and robolectric support would come out of experimental status in the next release sometime next week.

**Comment by kageiit** [comment]
All testing features are moved out of experimental now

https://github.com/uber/okbuck/commit/9180d26e92acf158c568837b63c5e096937c9f1b
