### ISSUE TITLE
Plugin Marker Artifacts aren't published

### ISSUE THREAD

**Issue by NickFirmani** [uber/okbuck#833]
Hi folks,

When trying to use the new fancy plugin DSL in Gradle, it can't find Okbuck's artifact, since it does not define a unique ID to pull the plugin from (even after specifying the correct repo in settings.gradle)

Reference: https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers

**Comment by kageiit** [comment]
okbuck needs to only go into the root project build.gradle. Can you use the non plugin dsl syntax for this? We dont have plans to ship a separate artifact for this as this plugin can be consumed without it

**Comment by NickFirmani** [comment]
Yes, using the non-plugin DSL syntax is possible, just not as clean :'(
