### ISSUE TITLE
okbuck does not generate test targets unless roboelctric = true

### ISSUE THREAD

**Issue by NickFirmani** [uber/okbuck#842]
With
```
test { 
   robolectric = true
}
```

Results in 
```
./buckw targets //...
...<truncated>
//app:src_release
//app:test_debug
//app:test_release
```

Setting that value to false or omitting that value results in 
```
./buckw targets //...
...<>
//app:src_debug
//app:src_release
```

This is of interest for applications that do not use robolectric (for whatever reason). This is reproducible in https://github.com/NickFirmani/android-template 

Thanks!

**Comment by kageiit** [comment]
You can choose to use a different test runner even if `robolectric = true` and never use robolectric. To keep configuration simple, it was a deliberate decision to only support one kind of test rule composition for Android projects.

Buck's Android test rule just adds some system properties to the test jvm as to where robolectric jars, manifests are available etc. You can use any test runner and choose to completely ignore robolectric and tears should still work.
