### ISSUE TITLE
Local dependencies should be under project root. Dependencies outside the project can cause hard to reproduce builds.

### ISSUE THREAD

**Issue by adellhk** [uber/okbuck#853]
@kageiit okbuck [disallows](https://github.com/uber/okbuck/pull/288) depending on a local dependency (in this case Jvm's `tools.jar`, `Jvm.current().getToolsJar()`). We want to add tools.jar to our classpath since Google's compile-testing library relies on `TreeScanner` https://github.com/google/compile-testing/issues/28#issuecomment-69204681.

Is there a better alternative than copying `tools.jar` into our project?

**Comment by kageiit** [comment]
you can publish to maven local or upload to some artifact server like jcenter/jitpack

**Comment by adellhk** [comment]
Yes, this is what we ended up doing. It feels a little circuitous, but overall reasonable.
