### ISSUE TITLE
OkBuck fails - okbuck_jetifier_deps

### ISSUE THREAD

**Issue by binaryroot** [uber/okbuck#864]
Trying to integrate okbuck. However, it fails during 

`
 ./buckw install //app:bin_debug --run
`

Build Gradle 

`
apply plugin: 'com.uber.okbuck'
okbuck {
    buildToolVersion = "28.0.3"
    lint {
        disabled = true
    }
    externalDependencies {
        downloadInBuck = false
    }
    jetifier {
        aarOnly = true
    }
}
`

Also added these two properties

`android.useAndroidX=true`
`android.enableJetifier=true`

Log

Execution failed for task ':setupOkbuck'.
> Could not resolve all artifacts for configuration ':okbuck_jetifier_deps'.
   > Cannot resolve external dependency com.android.tools.build.jetifier:jetifier-core:1.0.0-beta02 because no repositories are defined.
     Required by:
         project :
   > Cannot resolve external dependency com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta02 because no repositories are defined.
     Required by:
         project :
   > Cannot resolve external dependency commons-cli:commons-cli:1.3.1 because no repositories are defined.
     Required by:
         project :

**Comment by kageiit** [comment]
This should not longer be an issue with the latest okbuck. Please re-open if it happens on latest
