### ISSUE TITLE
No target found for project

### ISSUE THREAD

**Issue by JDDJJ** [uber/okbuck#865]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':calendarlibrary:okbuck'.
> No target found for project ':AndroidExLibrary' for variant null

####
when i run command './buckw targets //... '  ,show this error
this library is compile as this 'implementation project(':AndroidExLibrary')'

**Comment by kageiit** [comment]
This should not longer be an issue with the latest okbuck. Please re-open if it happens on latest
