### ISSUE TITLE
Cannot build kotlin-app:bin_debug

### ISSUE THREAD

**Issue by rifqimfahmi** [uber/okbuck#868]
Newly cloned OkBuck (v0.48.6) shows error when building `kotlin-app:bin_debug` target:
```
Kotlin home directory (Optional[/.okbuck/workspace/kotlin_home:kotlin_home]) specified in .buckconfig was not found.
    When creating rules for //kotlin-app:src_debug#class-abi.
    When creating rules for //kotlin-app:src_debug.
```

Is this related to this issue https://github.com/uber/okbuck/issues/798? Because I just newly clone the OkBuck (v0.48.6) then run the buck wrapper and build `kotlin-app:bin_debug`, or is this expected? 

STR:
- git clone OkBuck
- run `./gradlew :buckWrapper`
- run `./buckw clean`
- run `./buckw build kotlin-app:bin_debug`

Thank you

**Comment by rifqimfahmi** [comment]
solved by using this buck binary:
```
buckBinary = "com.github.lyft:buck:72b5ee6b682be1e85eb7950ef44232a76cc2cea6@pex"
```

**Comment by leleliu008** [comment]
Okbuck version is `0.50.7`

buck : ./.okbuck/workspace/buck_binary/`buck-f6578801138a7b6b89d4a485dd2d0c740fdefe8a.pex`

**reproduced**
