### ISSUE TITLE
Missing runtime dependencies of external modules with Gradle 5.0+

### ISSUE THREAD

**Issue by anoopc1** [uber/okbuck#872]
### **App Crashes with runtime exception**:
```
// missing run-time dep for apollo-runtime
java.lang.NoClassDefFoundError: com/nytimes/android/external/cache/Weigher

// missing run-time dep for flipper
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/jni/HybridClassBase

// Missing run-time dep for robolectric (while running tests)
java.lang.NoClassDefFoundError: org/robolectric/util/reflector/Reflector
```

**I suspect this issue is related to following change in `gradle` behavior starting version `5.0+`**:
- `Gradle-Issue-977`: [Separate compile and runtime dependencies of external modules](https://github.com/gradle/gradle/issues/977)

With older gradle versions, runtime dependencies of external modules (declared with `<scope>` `runtime` in pom-file, e.g. [`com.nytimes.android:cache in apollo-runtime-1.1.0.pom`](https://gist.github.com/anoopc1/12d8004860cb6fb6038929536985897a)) are imported as transitive compile-time dependencies in internal sub-projects (and get included as `deps` in generated `BUCK` file).
With above gradle-fix, only transitive compile-time dependencies are included in `deps` and run-time deps which are not explicitly added from anywhere else, do not get packaged in the final build output.

### Setup

OKBuck Version: `0.48.7`
AGP version: `3.3.2`
Gradle version: `5.1.1`

**okbuck external-dependency configuration**
```
okbuck {
  externalDependencies {
    resolutionAction = "all"
    downloadInBuck = false
    autoValueConfigurations = [ ... ]
  }
  ...
}
```

`ModuleA/build.gradle`
```
dependencies {
  api 'com.apollographql.apollo:apollo-runtime:1.0.2'
  ...
}
```

### **Steps to reproduce**:
1. Generate buck files for project containing `moduleA` using `buckw`
2. Build, install and run the app using `buckw` on emulator

_** Issue can also be reproduced with `Gradle 4.10.2 (4.6+)` by enabling `enableFeaturePreview('IMPROVED_POM_SUPPORT')` in `settings.gradle` (which is the default behavior in `Gradle 5.0+`)_

**Comment by kageiit** [comment]
This should not longer be an issue with the latest okbuck. Please re-open if it happens on latest
