### ISSUE TITLE
Dexguard 8.5.01 is Causing ANR

### ISSUE THREAD

**Issue by NikhilBhadouria** [uber/okbuck#875]
I have implemented Dexguard in my android app on Kotlin and Android X, with "dexguard-debug.pro" it works perfectly fine but with "dexguard-release.pro" app doesn't starts. Goes to ANR because of Services , Third party services , or Broadcast Reciever etc...  even tried with adding "-keep class [packages of files that is causing ANR]" , but it didnt helped , Can anyone help

**Comment by kageiit** [comment]
This issue is not related to okbuck
