### ISSUE TITLE
multiple dependencies problem

### ISSUE THREAD

**Issue by starfire-lzd** [uber/okbuck#887]
when i use this plugin it create the script with multiple dependencies while create
some rule to download the dependencies so when I run the ./buckw build //.. it will be error. and when I use android kapt androidx.room:room-compiler ,the init while be error

**Comment by starfire-lzd** [comment]
* What went wrong:
Execution failed for task ':***:okbuck'.
> autoValueConfigurations should be present if adding autoValue dependencies. missing: [DefaultExternalModuleDependency{group='androidx.room', name='room-compiler', version='2.1.0', configuration='default'}]

**Comment by starfire-lzd** [comment]
okbuck_prebuilt(
    name = 'push_3rd_huawei-1.0.0.jar',
    maven_coords = '**',
    sha256 = '**',
    sources_sha256 = '**',
)

okbuck_prebuilt(
    name = 'push_3rd_huawei-1.0.0.jar',
    maven_coords = '**',
    sha256 = '**',
    sources_sha256 = '**',
)

**Comment by kageiit** [comment]
Seems like gradle was not able to download and set sources correctly. This should not longer be an issue with the latest okbuck. Please re-open if it happens on latest
