### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by starfire-lzd** [uber/okbuck#888]
when I use the okbuck to build my gradle project ,it tell me can't fund the kotlin_kome in .buckconfig

**Comment by starfire-lzd** [comment]
the log:

Kotlin home directory (Optional[/.okbuck/workspace/kotlin_home:kotlin_home]) specified in .buckconfig was not found.
    When creating rules for //libraries/kotlinandroidlibrary:src_debug#class-abi.
    When creating rules for //libraries/kotlinandroidlibrary:src_debug.

**Comment by kageiit** [comment]
This should not longer be an issue with the latest okbuck. Please re-open if it happens on latest
