### ISSUE TITLE
.buckconfig has lower priority than .okbuck/config/okbuck.buckconfig

### ISSUE THREAD

**Issue by ilya-shknaj** [uber/okbuck#927]
Okbuck plugin **0.51.2**

The issue is that default **kotlin_home** path isn't valid for me. I suppose not only for me, because of **.okbuck/workspace/koltin_home** is always contained only a single BUCK file

I change **kotlin_home** in it **.buckconfig** to a valid one, but these changes are ignoring by okbuck. Only if remove **kotlin_home** from **.okbuck/config/okbuck.buckconfig** it read value from **.buckconfig**. 
This change works ok before any changes in gradle files, because in this case, **okbuck.buckconfig** is regenerating.
So, I don't have the ability to specify **kotlin_home** location. I suppose that **.buckconfig** must have more priority than **okbuck.buckconfig**, otherwise it doesn't have a sense

**Comment by raviagarwal7** [comment]
This should resolve the issue: https://github.com/uber/okbuck/pull/929/files (will require rerunning buckwrapper task).

Meanwhile you can fix the error by manually updating buckw similar to as it is done in the above pr.
